; methods/str_case.asm - Unicode case mapping, and the tables the predicates share
;
; upper, lower, title, capitalize, swapcase and casefold.  All six used to be
; ASCII byte loops that allocated the result at the input's byte length before
; deciding anything, so "e".upper() with an acute accent was itself -- and the
; allocation was the reason it could not simply be fixed in place: eszett
; upper-cases to two characters, and the dotless i shortens.
;
; The mappings live in src/compiler/unicodecase.asm, generated by
; gen_unicodecase.py from the running CPython's own str methods.  Two tables:
; ranges of equal delta, binary-searched, and the hundred-odd codepoints whose
; mapping is not one character.  A third, uflag_starts, carries the per-
; character categories -- what the is* predicates ask, and what title() asks to
; decide where a word begins.

%include "macros.inc"
%include "object.inc"

extern ucase_range_count
extern ucase_ranges
extern ucase_expand
extern uflag_count
extern uflag_starts
extern ap_malloc
extern ap_free
extern ap_memcpy
extern str_new_heap
extern str_set_length
extern raise_exception
extern exc_TypeError_type
extern exc_MemoryError_type

; ucase_ranges entry, 32 bytes
UC_LO     equ 0
UC_HI     equ 4
UC_UPPER  equ 8
UC_LOWER  equ 12
UC_TITLE  equ 16
UC_FOLD   equ 20
UC_EXP    equ 24
UC_SIZE   equ 32

; ucase_expand entry, 56 bytes; each field is NUL-padded UTF-8
UCE_UPPER equ 8
UCE_LOWER equ 20
UCE_TITLE equ 32
UCE_FOLD  equ 44
UCE_SIZE  equ 56
UCE_FIELD equ 12

; uflag_starts entry, 8 bytes: {start u32, flags u32}.  Kept in step with the
; UF_* in src/compiler/gen_unicodecase.py.
UF_ALPHA      equ 1
UF_DECIMAL    equ 2
UF_DIGIT      equ 4
UF_NUMERIC    equ 8
UF_SPACE      equ 16
UF_UPPER      equ 32
UF_LOWER      equ 64
UF_TITLECASE  equ 128
UF_PRINTABLE  equ 256
UF_XID_CONT   equ 512
UF_XID_START  equ 1024
UF_CASED      equ 2048
UF_CASE_IGN   equ 4096

; the modes str_case_map takes
CASE_UPPER      equ 0
CASE_LOWER      equ 1
CASE_TITLE      equ 2
CASE_CAPITALIZE equ 3
CASE_SWAPCASE   equ 4
CASE_CASEFOLD   equ 5

section .text

;; ============================================================================
;; ucase_find(edi = a code point) -> rax = the range entry, or 0
;; ============================================================================
global ucase_find
DEF_FUNC_BARE ucase_find
    xor esi, esi                    ; low bound
    mov rdx, [rel ucase_range_count]
    lea r8, [rel ucase_ranges]
.ucf_loop:
    cmp rsi, rdx
    jge .ucf_miss
    lea rax, [rsi + rdx]
    shr rax, 1
    mov rcx, rax
    shl rcx, 5                      ; * UC_SIZE
    add rcx, r8
    cmp edi, [rcx + UC_LO]
    jb .ucf_left
    cmp edi, [rcx + UC_HI]
    ja .ucf_right
    mov rax, rcx
    ret
.ucf_left:
    mov rdx, rax
    jmp .ucf_loop
.ucf_right:
    lea rsi, [rax + 1]
    jmp .ucf_loop
.ucf_miss:
    xor eax, eax
    ret
END_FUNC ucase_find

;; ============================================================================
;; uflags_of(edi = a code point) -> eax = its flags
;;
;; The table stores only where the flags change, so the answer is the last
;; entry whose start is at or below the codepoint.  Entry 0 starts at 0, so
;; the search always lands on one.
;; ============================================================================
global uflags_of
DEF_FUNC_BARE uflags_of
    xor esi, esi
    mov rdx, [rel uflag_count]
    lea r8, [rel uflag_starts]
    xor eax, eax                    ; the best answer so far
.ufo_loop:
    cmp rsi, rdx
    jge .ufo_done
    lea rcx, [rsi + rdx]
    shr rcx, 1
    mov r9, rcx
    shl r9, 3                       ; * 8
    add r9, r8
    cmp edi, [r9]
    jb .ufo_left
    mov eax, [r9 + 4]               ; a candidate: keep looking right
    lea rsi, [rcx + 1]
    jmp .ufo_loop
.ufo_left:
    mov rdx, rcx
    jmp .ufo_loop
.ufo_done:
    ret
END_FUNC uflags_of

;; ============================================================================
;; ucase_utf8_get(rdi = data, rsi = index) -> eax = code point, ecx = its width
;; A UTF-8 decode that trusts its input: every str here is well-formed.
;; ============================================================================
DEF_FUNC_BARE ucase_utf8_get
    movzx eax, byte [rdi + rsi]
    mov ecx, 1
    cmp al, 0x80
    jb .uug_done
    cmp al, 0xE0
    jae .uug_three
    ; two bytes
    and eax, 0x1F
    shl eax, 6
    movzx edx, byte [rdi + rsi + 1]
    and edx, 0x3F
    or  eax, edx
    mov ecx, 2
    ret
.uug_three:
    cmp al, 0xF0
    jae .uug_four
    and eax, 0x0F
    shl eax, 12
    movzx edx, byte [rdi + rsi + 1]
    and edx, 0x3F
    shl edx, 6
    or  eax, edx
    movzx edx, byte [rdi + rsi + 2]
    and edx, 0x3F
    or  eax, edx
    mov ecx, 3
    ret
.uug_four:
    and eax, 0x07
    shl eax, 18
    movzx edx, byte [rdi + rsi + 1]
    and edx, 0x3F
    shl edx, 12
    or  eax, edx
    movzx edx, byte [rdi + rsi + 2]
    and edx, 0x3F
    shl edx, 6
    or  eax, edx
    movzx edx, byte [rdi + rsi + 3]
    and edx, 0x3F
    or  eax, edx
    mov ecx, 4
.uug_done:
    ret
END_FUNC ucase_utf8_get

;; ============================================================================
;; ucase_utf8_put(rdi = dest, eax = code point) -> ecx = bytes written
;; ============================================================================
DEF_FUNC_BARE ucase_utf8_put
    cmp eax, 0x80
    jae .uup_two
    mov [rdi], al
    mov ecx, 1
    ret
.uup_two:
    cmp eax, 0x800
    jae .uup_three
    mov edx, eax
    shr edx, 6
    or  dl, 0xC0
    mov [rdi], dl
    and eax, 0x3F
    or  al, 0x80
    mov [rdi + 1], al
    mov ecx, 2
    ret
.uup_three:
    cmp eax, 0x10000
    jae .uup_four
    mov edx, eax
    shr edx, 12
    or  dl, 0xE0
    mov [rdi], dl
    mov edx, eax
    shr edx, 6
    and dl, 0x3F
    or  dl, 0x80
    mov [rdi + 1], dl
    and eax, 0x3F
    or  al, 0x80
    mov [rdi + 2], al
    mov ecx, 3
    ret
.uup_four:
    mov edx, eax
    shr edx, 18
    or  dl, 0xF0
    mov [rdi], dl
    mov edx, eax
    shr edx, 12
    and dl, 0x3F
    or  dl, 0x80
    mov [rdi + 1], dl
    mov edx, eax
    shr edx, 6
    and dl, 0x3F
    or  dl, 0x80
    mov [rdi + 2], dl
    and eax, 0x3F
    or  al, 0x80
    mov [rdi + 3], al
    mov ecx, 4
    ret
END_FUNC ucase_utf8_put


;; ============================================================================
;; str_case_map(rdi = a str, esi = mode) -> rax = a new str
;;
;; One walk over the code points.  The output can be longer than the input --
;; eszett becomes SS -- or shorter, so it goes into a buffer sized at four
;; bytes per input byte, which is the worst any mapping can do: no single
;; character expands to more than three, and each of those is at most four
;; bytes where the source was at least one.
;; ============================================================================
SC_SELF   equ 8
SC_DATA   equ 16
SC_LEN    equ 24
SC_MODE   equ 32
SC_BUF    equ 40
SC_OUT    equ 48
SC_POS    equ 56
SC_PREV   equ 64        ; title/capitalize: the previous character was cased
SC_FRAME  equ 80        ; + 4 pushes = 112

global str_case_map
DEF_FUNC str_case_map, SC_FRAME
    push r12
    push r13
    push r14
    push r15
    mov [rbp - SC_SELF], rdi
    mov [rbp - SC_MODE], rsi
    lea rax, [rdi + PyStrObject.data]
    mov [rbp - SC_DATA], rax
    mov rax, [rdi + PyStrObject.ob_size]
    mov [rbp - SC_LEN], rax

    ; Pure ASCII is the overwhelming majority and needs no table at all: every
    ; ASCII mapping stays one ASCII byte, so the result is the input's length
    ; and the transform can run in place on a copy.
    mov rcx, [rdi + PyStrObject.ob_length]
    cmp rcx, rax
    jne .sc_wide

    mov rdi, [rbp - SC_DATA]
    mov rsi, rax
    call str_new_heap
    test rax, rax
    jz .sc_oom
    mov [rbp - SC_OUT], rax
    lea r8, [rax + PyStrObject.data]
    mov r9, [rbp - SC_LEN]
    mov rdx, [rbp - SC_MODE]
    xor r11d, r11d              ; index
    xor r10d, r10d              ; the previous character was cased
.sc_ascii_loop:
    cmp r11, r9
    jge .sc_ascii_done
    movzx ecx, byte [r8 + r11]
    cmp rdx, CASE_CAPITALIZE
    je .sc_a_cap
    cmp rdx, CASE_TITLE
    je .sc_a_title
    cmp rdx, CASE_SWAPCASE
    je .sc_a_swap
    cmp rdx, CASE_LOWER
    je .sc_a_lower
    cmp rdx, CASE_CASEFOLD
    je .sc_a_lower              ; ASCII casefold is ASCII lower
.sc_a_upper:
    cmp cl, 'a'
    jb .sc_a_store
    cmp cl, 'z'
    ja .sc_a_store
    sub cl, 32
    jmp .sc_a_store
.sc_a_lower:
    cmp cl, 'A'
    jb .sc_a_store
    cmp cl, 'Z'
    ja .sc_a_store
    add cl, 32
    jmp .sc_a_store
.sc_a_swap:
    cmp cl, 'a'
    jb .sc_a_swap_up
    cmp cl, 'z'
    ja .sc_a_store
    sub cl, 32
    jmp .sc_a_store
.sc_a_swap_up:
    cmp cl, 'A'
    jb .sc_a_store
    cmp cl, 'Z'
    ja .sc_a_store
    add cl, 32
    jmp .sc_a_store
.sc_a_cap:
    test r11, r11
    jz .sc_a_upper
    jmp .sc_a_lower
.sc_a_title:
    ; A word continues only through LETTERS: CPython's rule is
    ; previous_is_cased = isalpha(ch), so "a1b".title() is "A1B" and not
    ; "A1b" -- the digit ends the word rather than continuing it.
    mov eax, ecx
    or  al, 0x20
    cmp al, 'a'
    jb .sc_a_title_other
    cmp al, 'z'
    ja .sc_a_title_other
    test r10b, r10b
    mov r10b, 1
    jnz .sc_a_lower
    jmp .sc_a_upper
.sc_a_title_other:
    xor r10d, r10d
.sc_a_store:
    mov [r8 + r11], cl
    inc r11
    jmp .sc_ascii_loop
.sc_ascii_done:
    mov rax, [rbp - SC_OUT]
    jmp .sc_out

;; --- the general path ------------------------------------------------------
.sc_wide:
    ; Four bytes of room per input byte: no mapping produces more.
    mov rdi, [rbp - SC_LEN]
    shl rdi, 2
    add rdi, 8
    call ap_malloc
    test rax, rax
    jz .sc_oom
    mov [rbp - SC_BUF], rax

    mov qword [rbp - SC_POS], 0
    mov qword [rbp - SC_PREV], 0
    xor r15d, r15d                  ; bytes written
.sc_wide_loop:
    mov rsi, [rbp - SC_POS]
    cmp rsi, [rbp - SC_LEN]
    jge .sc_wide_done
    mov rdi, [rbp - SC_DATA]
    call ucase_utf8_get             ; eax = cp, ecx = width
    movsxd rcx, ecx
    add [rbp - SC_POS], rcx
    mov r14d, eax                   ; the source code point

    ; Which of the four mappings applies to this character?
    mov rdx, [rbp - SC_MODE]
    cmp rdx, CASE_UPPER
    je .sc_w_pick_upper
    cmp rdx, CASE_LOWER
    je .sc_w_pick_lower
    cmp rdx, CASE_CASEFOLD
    je .sc_w_pick_fold
    cmp rdx, CASE_CAPITALIZE
    je .sc_w_pick_cap
    cmp rdx, CASE_SWAPCASE
    je .sc_w_pick_swap

    ; title: the first character of a word titlecases, the rest lower-case.
    ; The word boundary is CPython's -- the previous character being alpha.
    mov edi, r14d
    call uflags_of
    mov r13d, eax                   ; the flags, for the next character
    cmp qword [rbp - SC_PREV], 0
    jne .sc_w_pick_lower_kept
    mov r12d, UC_TITLE
    jmp .sc_w_pick_title_done
.sc_w_pick_lower_kept:
    mov r12d, UC_LOWER
.sc_w_pick_title_done:
    ; CPython's word boundary is the CASED property, not alphabetic:
    ; previous_is_cased = _PyUnicode_IsCased(c).  The two differ for every
    ; alphabetic-but-uncased character -- all of Lo, so Hebrew, Arabic, CJK,
    ; Thai, Devanagari -- and for every cased-but-not-alphabetic one, the
    ; Roman numerals and the circled letters among them.  "\u05d0a".title()
    ; is '\u05d0A' in CPython.
    and r13d, UF_CASED
    mov [rbp - SC_PREV], r13
    jmp .sc_w_have_pick

.sc_w_pick_cap:
    ; The first character titlecases and everything after it lower-cases.
    ; SC_POS has already stepped past this character, so subtracting its width
    ; gives where it started.
    mov r12d, UC_LOWER
    mov rax, [rbp - SC_POS]
    sub rax, rcx
    jnz .sc_w_have_pick
    mov r12d, UC_TITLE
    jmp .sc_w_have_pick

.sc_w_pick_swap:
    ; Upper-case what is lower and lower-case what is upper; leave the rest.
    mov edi, r14d
    call uflags_of
    mov r12d, UC_UPPER
    test eax, UF_LOWER
    jnz .sc_w_have_pick
    mov r12d, UC_LOWER
    test eax, UF_UPPER
    jnz .sc_w_have_pick
    jmp .sc_w_copy              ; uncased: itself

.sc_w_pick_upper:
    mov r12d, UC_UPPER
    jmp .sc_w_have_pick
.sc_w_pick_lower:
    mov r12d, UC_LOWER
    jmp .sc_w_have_pick
.sc_w_pick_fold:
    mov r12d, UC_FOLD

.sc_w_have_pick:
    mov edi, r14d
    call ucase_find
    test rax, rax
    jz .sc_w_copy                   ; no case: the character stands

    mov ecx, [rax + UC_EXP]
    cmp ecx, -1
    jne .sc_w_expand

    ; An ordinary range: add the delta for the mapping picked above.
    cmp r12d, UC_LOWER
    jne .sc_w_delta
    cmp r14d, 0x3A3
    je .sc_w_sigma
.sc_w_delta:
    mov edx, [rax + r12]
    lea eax, [r14d + edx]
    mov rdi, [rbp - SC_BUF]
    add rdi, r15
    call ucase_utf8_put
    movsxd rcx, ecx
    add r15, rcx
    jmp .sc_wide_loop

.sc_w_sigma:
    ; The one context-dependent mapping in the language: a capital sigma
    ; lower-cases to the final form when it ends a word.  CPython's rule, and
    ; its wording, is that U+03A3 is final when it matches
    ;   \p{cased}\p{case-ignorable}*U+03A3!(\p{case-ignorable}*\p{cased})
    ; -- a cased character before it, ignoring the ignorables, and no cased
    ; character after it on the same terms.
    call .sc_sigma_is_final
    mov eax, 0x3C3
    test ecx, ecx
    jz .sc_w_sigma_put
    mov eax, 0x3C2
.sc_w_sigma_put:
    mov rdi, [rbp - SC_BUF]
    add rdi, r15
    call ucase_utf8_put
    movsxd rcx, ecx
    add r15, rcx
    jmp .sc_wide_loop

.sc_w_expand:
    ; A codepoint whose mapping is not one character.  Every field holds the
    ; replacement as NUL-padded UTF-8, so this copies bytes and never has to
    ; ask which case it is looking at.
    movsxd rcx, ecx
    imul rcx, rcx, UCE_SIZE
    lea rax, [rel ucase_expand]
    add rax, rcx
    ; UC_UPPER..UC_FOLD are 8, 12, 16, 20; the expansion fields are 8, 20, 32,
    ; 44 -- three times the offset from UC_UPPER, plus UCE_UPPER.
    lea edx, [r12d - UC_UPPER]
    lea edx, [edx + edx*2]
    add edx, UCE_UPPER
    movsxd rdx, edx
    add rax, rdx                    ; the field
    mov rdi, [rbp - SC_BUF]
    add rdi, r15
    xor ecx, ecx
.sc_w_expand_copy:
    cmp ecx, UCE_FIELD
    jge .sc_wide_loop
    mov dl, [rax + rcx]
    test dl, dl
    jz .sc_wide_loop
    mov [rdi + rcx], dl
    inc rcx
    inc r15
    jmp .sc_w_expand_copy

.sc_w_copy:
    ; The character maps to itself: write it back out unchanged.
    mov eax, r14d
    mov rdi, [rbp - SC_BUF]
    add rdi, r15
    call ucase_utf8_put
    movsxd rcx, ecx
    add r15, rcx
    jmp .sc_wide_loop

.sc_wide_done:
    mov rdi, [rbp - SC_BUF]
    mov rsi, r15
    call str_new_heap
    mov [rbp - SC_OUT], rax
    mov rdi, [rbp - SC_BUF]
    call ap_free
    mov rax, [rbp - SC_OUT]
    test rax, rax
    jz .sc_oom
    ; str_new_heap sets ob_size; the code-point count has to be counted.
    mov rdi, rax
    call str_set_length
    mov rax, [rbp - SC_OUT]

.sc_out:
    pop r15
    pop r14
    pop r13
    pop r12
    leave
    ret

.sc_oom:
    RAISE exc_MemoryError_type, "out of memory"

;; .sc_sigma_is_final -> ecx = 1 when the sigma just consumed ends a word.
;; Reads the caller's SC_DATA/SC_LEN/SC_POS through rbp, which is why it is
;; not a standalone function.  SC_POS is already past the sigma, and the sigma
;; is two bytes, so it began at SC_POS - 2.
.sc_sigma_is_final:
    push rbx
    push r12
    push r13
    push r14
    mov r13, [rbp - SC_DATA]
    mov r14, [rbp - SC_LEN]
    mov rbx, [rbp - SC_POS]
    sub rbx, 2                  ; where the sigma starts

    ; Backwards: skip case-ignorable characters, then ask whether what stops
    ; the scan is cased.
.sc_sig_back:
    test rbx, rbx
    jle .sc_sig_no
    dec rbx
.sc_sig_back_lead:
    mov al, [r13 + rbx]
    and al, 0xC0
    cmp al, 0x80
    jne .sc_sig_back_have
    test rbx, rbx
    jz .sc_sig_back_have
    dec rbx
    jmp .sc_sig_back_lead
.sc_sig_back_have:
    mov rdi, r13
    mov rsi, rbx
    call ucase_utf8_get
    mov edi, eax
    call uflags_of
    test eax, UF_CASE_IGN
    jnz .sc_sig_back
    test eax, UF_CASED
    jz .sc_sig_no

    ; Forwards from just past the sigma, on the same terms.
    mov r12, [rbp - SC_POS]
.sc_sig_fwd:
    cmp r12, r14
    jge .sc_sig_yes             ; nothing after it at all
    mov rdi, r13
    mov rsi, r12
    call ucase_utf8_get
    movsxd rcx, ecx
    add r12, rcx
    mov edi, eax
    call uflags_of
    test eax, UF_CASE_IGN
    jnz .sc_sig_fwd
    test eax, UF_CASED
    jnz .sc_sig_no

.sc_sig_yes:
    mov ecx, 1
    pop r14
    pop r13
    pop r12
    pop rbx
    ret
.sc_sig_no:
    xor ecx, ecx
    pop r14
    pop r13
    pop r12
    pop rbx
    ret
END_FUNC str_case_map


;; ############################################################################
;;                       THE is* PREDICATES
;; ############################################################################
;;
;; All twelve were ASCII byte loops, for the same reason the case methods
;; were, and answered False for every character above 127: "é".isalpha() was
;; False, "١٢٣".isdigit() was False, and "Ⅷ".isnumeric() did not exist.  They
;; read the same generated flag table the case mappings do.

PRED_ALPHA      equ 0
PRED_DECIMAL    equ 1
PRED_DIGIT      equ 2
PRED_NUMERIC    equ 3
PRED_ALNUM      equ 4
PRED_SPACE      equ 5
PRED_UPPER      equ 6
PRED_LOWER      equ 7
PRED_TITLE      equ 8
PRED_PRINTABLE  equ 9
PRED_IDENTIFIER equ 10
PRED_ASCII      equ 11

;; ============================================================================
;; str_pred_impl(rdi = a str, esi = which) -> eax = 0 or 1
;;
;; The all-characters-share-a-flag family is one loop; the three cased ones
;; and isidentifier each have their own, because their rules are about the
;; sequence and not about each character alone.
;; ============================================================================
SP_DATA   equ 8
SP_LEN    equ 16
SP_WHICH  equ 24
SP_POS    equ 32
SP_STATE  equ 40
SP_FRAME  equ 48        ; + 2 pushes = 64

global str_pred_impl
DEF_FUNC str_pred_impl, SP_FRAME
    push r12
    push r13
    lea rax, [rdi + PyStrObject.data]
    mov [rbp - SP_DATA], rax
    mov rax, [rdi + PyStrObject.ob_size]
    mov [rbp - SP_LEN], rax
    mov [rbp - SP_WHICH], rsi

    cmp esi, PRED_ASCII
    je .sp_ascii_only
    cmp esi, PRED_UPPER
    je .sp_cased
    cmp esi, PRED_LOWER
    je .sp_cased
    cmp esi, PRED_TITLE
    je .sp_title
    cmp esi, PRED_IDENTIFIER
    je .sp_identifier

    ; The flag families.  Empty is False for all of them except isprintable,
    ; which is True -- CPython's asymmetry, not an oversight here.
    test rax, rax
    jnz .sp_flag_loop
    xor eax, eax
    cmp qword [rbp - SP_WHICH], PRED_PRINTABLE
    jne .sp_out
    mov eax, 1
    jmp .sp_out

.sp_flag_loop:
    mov qword [rbp - SP_POS], 0
.sp_flag_step:
    mov rsi, [rbp - SP_POS]
    cmp rsi, [rbp - SP_LEN]
    jge .sp_true
    mov rdi, [rbp - SP_DATA]
    call ucase_utf8_get
    movsxd rcx, ecx
    add [rbp - SP_POS], rcx
    mov edi, eax
    call uflags_of
    mov ecx, [rbp - SP_WHICH]
    mov edx, UF_ALPHA
    cmp ecx, PRED_DECIMAL
    je .sp_flag_decimal
    cmp ecx, PRED_DIGIT
    je .sp_flag_digit
    cmp ecx, PRED_NUMERIC
    je .sp_flag_numeric
    cmp ecx, PRED_ALNUM
    je .sp_flag_alnum
    cmp ecx, PRED_SPACE
    je .sp_flag_space
    cmp ecx, PRED_PRINTABLE
    je .sp_flag_printable
    jmp .sp_flag_test
.sp_flag_decimal:
    mov edx, UF_DECIMAL
    jmp .sp_flag_test
.sp_flag_digit:
    mov edx, UF_DIGIT
    jmp .sp_flag_test
.sp_flag_numeric:
    mov edx, UF_NUMERIC
    jmp .sp_flag_test
.sp_flag_alnum:
    mov edx, UF_ALPHA | UF_DECIMAL | UF_DIGIT | UF_NUMERIC
    jmp .sp_flag_test
.sp_flag_space:
    mov edx, UF_SPACE
    jmp .sp_flag_test
.sp_flag_printable:
    mov edx, UF_PRINTABLE
.sp_flag_test:
    test eax, edx
    jz .sp_false
    jmp .sp_flag_step

;; isascii: every byte below 0x80, and an empty string qualifies.
.sp_ascii_only:
    mov rdi, [rbp - SP_DATA]
    xor ecx, ecx
.sp_ascii_step:
    cmp rcx, [rbp - SP_LEN]
    jge .sp_true
    cmp byte [rdi + rcx], 0x80
    jae .sp_false
    inc rcx
    jmp .sp_ascii_step

;; isupper / islower: no character of the opposite case, and at least one of
;; the right one.  A titlecase character disqualifies both.
.sp_cased:
    mov qword [rbp - SP_POS], 0
    mov qword [rbp - SP_STATE], 0       ; one of the right case has been seen
.sp_cased_step:
    mov rsi, [rbp - SP_POS]
    cmp rsi, [rbp - SP_LEN]
    jge .sp_cased_end
    mov rdi, [rbp - SP_DATA]
    call ucase_utf8_get
    movsxd rcx, ecx
    add [rbp - SP_POS], rcx
    mov edi, eax
    call uflags_of
    mov ecx, UF_UPPER
    mov edx, UF_LOWER | UF_TITLECASE
    cmp qword [rbp - SP_WHICH], PRED_UPPER
    je .sp_cased_have
    mov ecx, UF_LOWER
    mov edx, UF_UPPER | UF_TITLECASE
.sp_cased_have:
    test eax, edx
    jnz .sp_false
    test eax, ecx
    jz .sp_cased_step
    mov qword [rbp - SP_STATE], 1
    jmp .sp_cased_step
.sp_cased_end:
    cmp qword [rbp - SP_STATE], 0
    je .sp_false
    jmp .sp_true

;; istitle: every uppercase or titlecase character opens a word, every
;; lowercase one continues one, and at least one of them is there.
.sp_title:
    mov qword [rbp - SP_POS], 0
    xor r12d, r12d                      ; a cased character has been seen
    xor r13d, r13d                      ; the previous character was cased
.sp_title_step:
    mov rsi, [rbp - SP_POS]
    cmp rsi, [rbp - SP_LEN]
    jge .sp_title_end
    mov rdi, [rbp - SP_DATA]
    call ucase_utf8_get
    movsxd rcx, ecx
    add [rbp - SP_POS], rcx
    mov edi, eax
    call uflags_of
    test eax, UF_UPPER | UF_TITLECASE
    jnz .sp_title_open
    test eax, UF_LOWER
    jnz .sp_title_continue
    xor r13d, r13d
    jmp .sp_title_step
.sp_title_open:
    test r13d, r13d
    jnz .sp_false
    mov r13d, 1
    mov r12d, 1
    jmp .sp_title_step
.sp_title_continue:
    test r13d, r13d
    jz .sp_false
    mov r12d, 1
    jmp .sp_title_step
.sp_title_end:
    test r12d, r12d
    jz .sp_false
    jmp .sp_true

;; isidentifier: XID_Start then XID_Continue, and never empty.
.sp_identifier:
    cmp qword [rbp - SP_LEN], 0
    je .sp_false
    mov qword [rbp - SP_POS], 0
.sp_ident_step:
    mov rsi, [rbp - SP_POS]
    cmp rsi, [rbp - SP_LEN]
    jge .sp_true
    mov rdi, [rbp - SP_DATA]
    call ucase_utf8_get
    movsxd rcx, ecx
    mov r12, [rbp - SP_POS]
    add [rbp - SP_POS], rcx
    mov edi, eax
    call uflags_of
    mov edx, UF_XID_CONT
    test r12, r12
    jnz .sp_ident_test
    mov edx, UF_XID_START
.sp_ident_test:
    test eax, edx
    jz .sp_false
    jmp .sp_ident_step

.sp_true:
    mov eax, 1
    jmp .sp_out
.sp_false:
    xor eax, eax
.sp_out:
    pop r13
    pop r12
    leave
    ret
END_FUNC str_pred_impl
