; modules/ucd32.asm - the frozen Unicode 3.2 database, as unicodedata.ucd_3_2_0
;
; RFC 3454 froze the Unicode version an IDN label folds against, so
; `stringprep` asks `unicodedata.ucd_3_2_0` rather than `unicodedata`: a
; property that has moved since 2002 must not move the answer.  CPython ships
; both copies for the same reason and exposes the old one under this name.
;
; The tables are src/modules/ucd32_tables.asm, generated by
; src/compiler/gen_ucd32.py from the running CPython's own ucd_3_2_0.  The
; LOOKUPS are not duplicated: the run search is unicodedata.asm's
; udp_run_lookup and the normalization engine is unicodenorm.asm's, pointed at
; the other table set by udn_select.
;
; Only what something reads is here.  `stringprep` uses category,
; bidirectional and normalize; `test_unicodedata` adds east_asian_width and
; mirrored; combining and decomposition come with the engine.  The names and
; the numeric values are not: nothing asks the 3.2 database for them, and each
; would be a second copy of a table larger than all of these together.

%include "macros.inc"
%include "object.inc"
%include "value.inc"

extern dict_new
extern dict_set
extern module_new
extern obj_decref
extern str_from_cstr_heap
extern str_type
extern str_cp_at
extern builtin_func_new
extern exc_TypeError_type
extern raise_exception
extern int_from_i64
extern udp_run_lookup
extern ucd32_normalize
extern ucd32_decomposition

extern ucd32_category_starts
extern ucd32_category_count
extern ucd32_category_strings
extern ucd32_bidi_starts
extern ucd32_bidi_count
extern ucd32_bidi_strings
extern ucd32_eaw_starts
extern ucd32_eaw_count
extern ucd32_eaw_strings
extern ucd32_combining_starts
extern ucd32_combining_count
extern ucd32_mirrored_starts
extern ucd32_mirrored_count

section .text

;; ============================================================================
;; ucd32_one_codepoint(rdi = a Value) -> rax = the code point, or -1
;;
;; The same "a str of length exactly one" test unicodedata.asm applies, whose
;; own copy is file-local to it.
;; ============================================================================
DEF_FUNC_LOCAL ucd32_one_codepoint
    V_TEST_PTR rdi, rax
    ja .no
    test rdi, rdi
    jz .no
    mov rax, [rdi + PyObject.ob_type]
    lea rcx, [rel str_type]
    cmp rax, rcx
    jne .no
    cmp qword [rdi + PyStrObject.ob_length], 1
    jne .no
    xor esi, esi
    call str_cp_at
    leave
    ret
.no:
    mov rax, -1
    leave
    ret
END_FUNC ucd32_one_codepoint

;; ============================================================================
;; The three string-valued properties and the two integer ones, in the shape
;; unicodedata.asm gives the current database's -- one code point in, a run
;; lookup, and either the pooled string its index names or the number itself.
;; ============================================================================
%macro UCD32_STR_PROP 3         ; %1 = python name, %2 = table label, %3 = wording
DEF_FUNC ucd32_%1
    cmp rsi, 1
    jne .arity
    mov rdi, [rdi]
    call ucd32_one_codepoint
    cmp rax, -1
    je .type
    mov edx, eax
    lea rdi, [rel %2_starts]
    mov rsi, [rel %2_count]
    call udp_run_lookup
    lea rcx, [rel %2_strings]
    mov rdi, [rcx + rax * 8]
    call str_from_cstr_heap
    leave
    ret
.type:
    RAISE exc_TypeError_type, %3
.arity:
    RAISE exc_TypeError_type, %3
END_FUNC ucd32_%1
%endmacro

UCD32_STR_PROP category, ucd32_category, \
    "category() argument must be a unicode character"
UCD32_STR_PROP bidirectional, ucd32_bidi, \
    "bidirectional() argument must be a unicode character"
UCD32_STR_PROP east_asian_width, ucd32_eaw, \
    "east_asian_width() argument must be a unicode character"

%macro UCD32_INT_PROP 3         ; %1 = python name, %2 = table label, %3 = wording
DEF_FUNC ucd32_%1
    cmp rsi, 1
    jne .arity
    mov rdi, [rdi]
    call ucd32_one_codepoint
    cmp rax, -1
    je .type
    mov edx, eax
    lea rdi, [rel %2_starts]
    mov rsi, [rel %2_count]
    call udp_run_lookup
    movsxd rdi, eax
    call int_from_i64
    V_PACK rax, rdx
    leave
    ret
.type:
    RAISE exc_TypeError_type, %3
.arity:
    RAISE exc_TypeError_type, %3
END_FUNC ucd32_%1
%endmacro

UCD32_INT_PROP combining, ucd32_combining, \
    "combining() argument must be a unicode character"
UCD32_INT_PROP mirrored, ucd32_mirrored, \
    "mirrored() argument must be a unicode character"

;; ============================================================================
;; ucd32_module_create() -> rax = the module object, or 0
;;
;; A real module rather than a namespace, because `stringprep` does
;; `from unicodedata import ucd_3_2_0 as unicodedata` and then uses it exactly
;; as it would the module -- and because `unidata_version` has to read '3.2.0'
;; off it, which the assert on its second line checks.
;;
;; It is NOT registered in sys.modules: CPython's is an attribute of
;; unicodedata and nothing else, so `import ucd_3_2_0` fails there too.
;; ============================================================================
UMC_FRAME equ 32            ; + 2 pushes = 48, 16-aligned
global ucd32_module_create
DEF_FUNC ucd32_module_create, UMC_FRAME
    push rbx
    push r12
    call dict_new
    test rax, rax
    jz .fail
    mov r12, rax                ; MODULE_ADD_FUNC reads the dict from r12

    MODULE_ADD_FUNC ucd32_category, u32_n_category
    MODULE_ADD_FUNC ucd32_bidirectional, u32_n_bidirectional
    MODULE_ADD_FUNC ucd32_east_asian_width, u32_n_eaw
    MODULE_ADD_FUNC ucd32_combining, u32_n_combining
    MODULE_ADD_FUNC ucd32_mirrored, u32_n_mirrored
    MODULE_ADD_FUNC ucd32_normalize, u32_n_normalize
    MODULE_ADD_FUNC ucd32_decomposition, u32_n_decomposition

    lea rdi, [rel u32_n_version]
    call str_from_cstr_heap
    mov rbx, rax
    lea rdi, [rel u32_v_version]
    call str_from_cstr_heap
    mov rdi, r12
    mov rsi, rbx
    mov rdx, rax
    push rax
    push rax                    ; twice: rsp stays 16-byte aligned
    call dict_set
    pop rdi
    pop rax
    call obj_decref
    mov rdi, rbx
    call obj_decref

    lea rdi, [rel u32_name]
    call str_from_cstr_heap
    mov rbx, rax
    mov rdi, rax
    mov rsi, r12
    call module_new
    push rax
    push rax
    mov rdi, rbx
    call obj_decref
    mov rdi, r12
    call obj_decref
    pop rax
    pop rcx
    pop r12
    pop rbx
    leave
    ret
.fail:
    xor eax, eax
    pop r12
    pop rbx
    leave
    ret
END_FUNC ucd32_module_create

section .rodata
u32_name:              db "unicodedata.ucd_3_2_0", 0
u32_n_category:        db "category", 0
u32_n_bidirectional:   db "bidirectional", 0
u32_n_eaw:             db "east_asian_width", 0
u32_n_combining:       db "combining", 0
u32_n_mirrored:        db "mirrored", 0
u32_n_normalize:       db "normalize", 0
u32_n_decomposition:   db "decomposition", 0
u32_n_version:         db "unidata_version", 0
u32_v_version:         db "3.2.0", 0
