# Test SmallStr method calls (strings <= 14 bytes)
print("hi".upper())
print("HI".lower())
print("  hi  ".strip())
print("hello".startswith("he"))
print("hello".find("ll"))
print("hello".replace("l", "r"))
print("hello".split("l"))
print(",".join(["a", "b"]))
print("hello".endswith("lo"))
print("abc".count("b"))
print("hello"[1])
print(len("hi"))
