#!/usr/bin/env python3
"""Generate lib/_ast.py -- the AST node classes.

Run from the repository root with a CPython 3.12:

    python3 src/compiler/gen_ast.py > lib/_ast.py

The class model is read out of the running interpreter's own `_ast` rather
than transcribed from Parser/Python.asdl, for the reason gen_tables.py gives
about opcode metadata: a field order that is one out here produces nodes that
look right under repr and are wrong under ast.dump, ast.iter_fields and every
NodeVisitor.  The whole model -- 124 classes, their bases, their _fields and
their _attributes -- is available by introspection, so there is nothing left
to get wrong by hand.

The other half of _ast, the one that turns apython's own arena AST into these
classes, is hand-written in lib/_ast_build.py and imported at the end of the
generated file.  Keeping it in a separate module is what lets `make regen`
rewrite this one wholesale.
"""
import sys

if sys.version_info[:2] != (3, 12):
    sys.exit("must be run under CPython 3.12; got %s" % sys.version.split()[0])

import _ast

# ---------------------------------------------------------------------------
# Every class, in an order where a base is always defined before the classes
# that derive from it: AST first, then a depth-first walk of the subclass
# tree, alphabetical at each level so the output is stable.
# ---------------------------------------------------------------------------
classes = []
seen = set()


def visit(cls):
    if cls in seen:
        return
    seen.add(cls)
    classes.append(cls)
    for sub in sorted(cls.__subclasses__(), key=lambda c: c.__name__):
        visit(sub)


visit(_ast.AST)

# Every AST class in _ast must be reachable from AST; one that is not would
# be silently dropped from the output.  __loader__ is a class and is not one.
names = {c.__name__ for c in classes}
missing = sorted(n for n in dir(_ast)
                 if isinstance(getattr(_ast, n), type)
                 and issubclass(getattr(_ast, n), _ast.AST)
                 and n not in names)
if missing:
    sys.exit("classes in _ast not reachable from AST: %s" % missing)

_MISSING = object()

out = []
w = out.append

w('"""_ast -- the AST node classes.')
w("")
w("GENERATED by src/compiler/gen_ast.py from CPython 3.12's own _ast.  Do not")
w("edit; run `make regen`.  The half that builds these from apython's parser")
w("is hand-written in _ast_build.py and imported at the bottom.")
w("")
w("CPython's _ast is a C module and there is no Lib/_ast.py, so this cannot be")
w("shadowed by a real stdlib on PYTHONPATH -- which is why it can be a plain")
w("Python module rather than half of an assembly one, the way _io is.")
w('"""')
w("")

for flag in ("PyCF_ONLY_AST", "PyCF_TYPE_COMMENTS", "PyCF_ALLOW_TOP_LEVEL_AWAIT"):
    w("%s = 0x%x" % (flag, getattr(_ast, flag)))
w("")
w("")

# The base is written out rather than generated: its __init__ is the whole of
# the model's behaviour, and there is nothing to introspect about it.
w('class AST:')
w('    """The base of every node.')
w("")
w("    CPython's constructor assigns positional arguments against _fields and")
w("    then keyword arguments by name, accepting names that are in neither --")
w("    the position attributes among them.  A field that was never assigned is")
w("    an AttributeError on access rather than None, which is what")
w("    ast.iter_fields and ast.dump both read it as.")
w('    """')
w("")
w('    __module__ = "ast"')
w("")
w("    _fields = ()")
w("    _attributes = ()")
w("")
w("    def __init__(self, *args, **kwargs):")
w("        fields = self._fields")
w("        if len(args) > len(fields):")
w("            raise TypeError(")
w('                "%s constructor takes at most %d positional argument%s"')
w('                % (type(self).__name__, len(fields),')
w('                   "" if len(fields) == 1 else "s"))')
w("        for name, value in zip(fields, args):")
w("            setattr(self, name, value)")
w("        for name, value in kwargs.items():")
w("            setattr(self, name, value)")
w("")
w("    def __repr__(self):")
w("        parts = []")
w("        for name in self._fields:")
w("            try:")
w('                parts.append("%s=%r" % (name, getattr(self, name)))')
w("            except AttributeError:")
w("                pass")
w('        return "%s(%s)" % (type(self).__name__, ", ".join(parts))')
w("")
w("")

for cls in classes:
    if cls is _ast.AST:
        continue
    base = cls.__bases__[0]
    w("class %s(%s):" % (cls.__name__, base.__name__))
    body = []
    if cls._fields != base._fields:
        body.append("    _fields = %r" % (cls._fields,))
    attrs = getattr(cls, "_attributes", ())
    if attrs != getattr(base, "_attributes", ()):
        body.append("    _attributes = %r" % (attrs,))
    # A field with a class-level default of None is one ast.dump leaves out
    # when it is None on the instance too -- Constant(value=1), not
    # Constant(value=1, kind=None).  There is no way to tell that from the
    # instance, so the defaults have to be here.
    for name in cls._fields:
        if getattr(cls, name, _MISSING) is None:
            body.append("    %s = None" % name)
    out.extend(body or ["    pass"])
    w("")
    w("")

w("# The bridge to apython's parser: compile(..., PyCF_ONLY_AST) calls")
w("# _from_raw on the raw tuple tree the assembly walker hands back.")
w("from _ast_build import _from_raw  # noqa: E402,F401")

sys.stdout.write("\n".join(out) + "\n")
