#!/usr/bin/env python3
"""Generate src/modules/unicodedataprops.asm -- the Unicode property tables.

Like gen_unicodename.py and gen_unicodecase.py beside it, the data is taken
from the RUNNING interpreter's own unicodedata rather than transcribed from
the UCD files: a transcription is a second copy to keep in step, and the
point of these tables is to agree with CPython exactly.

Five of the seven properties are run-compressed -- one row per place the
value CHANGES, binary searched -- because they are enormously runny: 0x110000
code points collapse to 4007 rows for the general category and 229 for
mirrored.  The other two, numeric and digit, are sparse rather than runny and
are stored per code point.

Refuses to run on anything but CPython 3.12, for the reason gen_tables.py
gives: the outputs are committed, so a regeneration under a different version
would silently retable the interpreter.
"""
import sys
import unicodedata

if sys.implementation.name != "cpython" or sys.version_info[:2] != (3, 12):
    sys.exit("gen_unicodedata.py must run on CPython 3.12")

MAX = 0x110000


def runs(fn):
    """One (start, value) row per place the property changes."""
    out = []
    prev = object()
    for cp in range(MAX):
        v = fn(chr(cp))
        if v != prev:
            out.append((cp, v))
            prev = v
    return out


def emit_string_pool(label, values):
    """The distinct values, as NUL-terminated strings, plus an index table."""
    print("align 8")
    print("global %s_strings" % label)
    print("%s_strings:" % label)
    for i, v in enumerate(values):
        print('    dq %s_s%d' % (label, i))
    for i, v in enumerate(values):
        print('%s_s%d: db "%s", 0' % (label, i, v))
    print()


def emit_runs(label, rows, values):
    index = {v: i for i, v in enumerate(values)}
    print(";; %s: %d runs over %d distinct values" % (label, len(rows), len(values)))
    print("align 8")
    print("global %s_starts" % label)
    print("%s_starts:" % label)
    for cp, v in rows:
        print("    dd 0x%06x, %d" % (cp, index[v]))
    print("global %s_count" % label)
    print("%s_count: dq %d" % (label, len(rows)))
    print()


def emit_int_runs(label, rows):
    print(";; %s: %d runs" % (label, len(rows)))
    print("align 8")
    print("global %s_starts" % label)
    print("%s_starts:" % label)
    for cp, v in rows:
        print("    dd 0x%06x, %d" % (cp, v))
    print("global %s_count" % label)
    print("%s_count: dq %d" % (label, len(rows)))
    print()


def as_fraction(x):
    """The numeric value as an exact (numerator, denominator) pair.

    unicodedata.numeric answers a float, and a float cannot say 1/3 -- so the
    pair is recovered from the float, which is exact for every value the UCD
    actually carries (they are all n/d with a small d).
    """
    from fractions import Fraction
    f = Fraction(x).limit_denominator(1000000)
    assert abs(float(f) - x) < 1e-9, (x, f)
    return f.numerator, f.denominator


def main():
    print(";; unicodedataprops.asm - GENERATED by src/compiler/gen_unicodedata.py.")
    print(";; Do not edit.  Unicode %s, from the running interpreter's own"
          % unicodedata.unidata_version)
    print(";; unicodedata -- the same source gen_unicodename.py and")
    print(";; gen_unicodecase.py take theirs from.")
    print(";;")
    print(";; Each run table is (dd start, dd value), sorted, one row per place")
    print(";; the property changes; the value holds until the next row.  The")
    print(";; string-valued ones index a pool beside them.")
    print()
    print('%include "macros.inc"')
    print()
    print("section .rodata")
    print()

    cat = runs(unicodedata.category)
    cat_vals = sorted({v for _, v in cat})
    emit_string_pool("udp_category", cat_vals)
    emit_runs("udp_category", cat, cat_vals)

    bidi = runs(unicodedata.bidirectional)
    bidi_vals = sorted({v for _, v in bidi})
    emit_string_pool("udp_bidi", bidi_vals)
    emit_runs("udp_bidi", bidi, bidi_vals)

    eaw = runs(unicodedata.east_asian_width)
    eaw_vals = sorted({v for _, v in eaw})
    emit_string_pool("udp_eaw", eaw_vals)
    emit_runs("udp_eaw", eaw, eaw_vals)

    emit_int_runs("udp_combining", runs(unicodedata.combining))
    emit_int_runs("udp_mirrored", runs(unicodedata.mirrored))

    dig = [(cp, unicodedata.digit(chr(cp)))
           for cp in range(MAX) if unicodedata.digit(chr(cp), None) is not None]
    print(";; digit: %d code points, sparse rather than runny" % len(dig))
    print("align 8")
    print("global udp_digit_table")
    print("udp_digit_table:")
    for cp, v in dig:
        print("    dd 0x%06x, %d" % (cp, v))
    print("global udp_digit_count")
    print("udp_digit_count: dq %d" % len(dig))
    print()

    num = [(cp, unicodedata.numeric(chr(cp)))
           for cp in range(MAX) if unicodedata.numeric(chr(cp), None) is not None]
    print(";; numeric: %d code points, each an exact numerator/denominator" % len(num))
    print("align 8")
    print("global udp_numeric_table")
    print("udp_numeric_table:")
    for cp, v in num:
        n, d = as_fraction(v)
        print("    dd 0x%06x, 0" % cp)
        print("    dq %d, %d" % (n, d))
    print("global udp_numeric_count")
    print("udp_numeric_count: dq %d" % len(num))
    print()
    print("ASM_INIT")


main()
