#!/usr/bin/env python3
"""gen_encodings.py - the tables CPython's encodings/ package is made of.

CPython ships one module per codec.  Nearly all of them are the same module
with a different 256-entry table in it: a `decoding_table` mapping each byte
to a code point, and an `encoding_table` built from it by charmap_build.  So
the tables are what is worth shipping, and `lib/encodings/__init__.py` is the
one module that turns any of them into a CodecInfo.

Two files come out of this:

    lib/encodings/_tables.py   name -> decoding table
    lib/encodings/aliases.py   CPython's own alias map, verbatim

A table whose first 128 entries are ASCII is stored as its top half only,
which is the common case; the loader puts the ASCII half back.  A codec whose
table is not flat -- the CJK multi-byte families, and the transforms like
base64_codec -- is not here and is not expressible this way.

Run through `make regen`.  The outputs are committed, so building apython
never needs a CPython with an encodings package.
"""
import os
import sys

if sys.implementation.name != "cpython":
    sys.exit("gen_encodings.py needs CPython's own encodings package")

import encodings
import encodings.aliases

OUT = sys.argv[1] if len(sys.argv) > 1 else "lib/encodings"
ASCII = "".join(chr(i) for i in range(128))


def tables():
    """{codec name: 256-char decoding table} for every flat single-byte codec."""
    d = os.path.dirname(encodings.__file__)
    out = {}
    for fn in sorted(os.listdir(d)):
        if not fn.endswith(".py") or fn.startswith("__") or fn == "aliases.py":
            continue
        name = fn[:-3]
        try:
            mod = __import__("encodings." + name, fromlist=["x"])
        except Exception:
            continue
        t = getattr(mod, "decoding_table", None)
        if isinstance(t, str) and len(t) == 256:
            # The registered name is the module's own, not the file's:
            # iso8859_15.py answers 'iso8859-15'.
            try:
                reg = mod.getregentry().name
            except Exception:
                reg = name
            out[name] = (t, reg)
    return out


def literal(s):
    """A Python string literal for `s`, ASCII-only so the file needs no BOM."""
    out = ['"']
    for ch in s:
        n = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif 0x20 <= n < 0x7F:
            out.append(ch)
        elif n < 0x100:
            out.append("\\x%02x" % n)
        elif n < 0x10000:
            out.append("\\u%04x" % n)
        else:
            out.append("\\U%08x" % n)
    out.append('"')
    return "".join(out)


def write_tables(path):
    t = tables()
    with open(path, "w") as fh:
        fh.write('"""The decoding tables of CPython\'s single-byte codecs.\n\n'
                 "GENERATED by src/compiler/gen_encodings.py -- do not edit.\n\n"
                 "Each value is a codec's decoding table: byte -> code point, with\n"
                 "'\\ufffe' where the byte maps to nothing.  A name in ASCII_HALF has\n"
                 "an ASCII lower half that is not stored; encodings/__init__.py puts\n"
                 'it back.  NAMES holds the ones whose registered name differs.\n"""\n\n')
        fh.write("ASCII_HALF = frozenset((\n")
        for name in sorted(t):
            if t[name][0][:128] == ASCII:
                fh.write("    %r,\n" % name)
        fh.write("))\n\n# The name each codec answers to, which is the one its\n"
                 "# CPython module registers and not always the module's own.\n"
                 "NAMES = {\n")
        for name in sorted(t):
            if t[name][1] != name:
                fh.write("    %r: %r,\n" % (name, t[name][1]))
        fh.write("}\n\nTABLES = {\n")
        for name in sorted(t):
            body = t[name][0][128:] if t[name][0][:128] == ASCII else t[name][0]
            fh.write("    %r:\n" % name)
            for i in range(0, len(body), 32):
                fh.write("        %s\n" % literal(body[i:i + 32]))
            fh.write("    ,\n")
        fh.write("}\n")
    return len(t)


def write_aliases(path):
    a = encodings.aliases.aliases
    with open(path, "w") as fh:
        fh.write('"""encodings.aliases - the alternative spellings of each codec.\n\n'
                 "GENERATED by src/compiler/gen_encodings.py -- do not edit.\n\n"
                 "CPython's own map, verbatim.  It names codecs this tree does not\n"
                 "ship as well as ones it does; an alias for a missing codec resolves\n"
                 'and then fails to be found, which is what CPython does too.\n"""\n\n')
        fh.write("aliases = {\n")
        for k in sorted(a):
            fh.write("    %r: %r,\n" % (k, a[k]))
        fh.write("}\n")
    return len(a)


n = write_tables(os.path.join(OUT, "_tables.py"))
m = write_aliases(os.path.join(OUT, "aliases.py"))
sys.stderr.write("%d decoding tables, %d aliases\n" % (n, m))
