#!/usr/bin/env python3
"""Regenerate src/compiler/unicodename.asm -- the table \\N{...} looks names up in.

    python3 src/compiler/gen_unicodename.py > src/compiler/unicodename.asm

The names come from the running interpreter's own `unicodedata`, the same way
gen_tables.py takes its opcode metadata from `opcode` and `dis`: transcribing
them by hand is how a table like this goes quietly out of date.

CJK UNIFIED IDEOGRAPH-XXXX is algorithmic and stays out of the table -- 97046
of the 143041 names, and the character's own codepoint is written in the name.
Only the ranges it is valid over are emitted, so a bogus one is still rejected.
Everything else, Hangul syllables included, is a literal entry.

The lookup is a linear scan, because `\\N{...}` is rare -- a handful of
occurrences in a whole file -- so an index would cost more than it saves.  The
scan being sequential is also what makes the encoding cheap:

    per entry:  db shared, db cpdelta [, dd cp when cpdelta == 255],
                db "suffix", 0

`shared` is how many leading bytes this name has in common with the PREVIOUS
one, which in codepoint order is a great many: "LATIN CAPITAL LETTER B" after
"LATIN CAPITAL LETTER A" carries one byte of payload.  The codepoint is a
delta for the same reason, with 255 escaping to an absolute for the handful of
places the sequence jumps -- the aliases at the end, which are not in
codepoint order at all.

Names stored raw were 1,177,404 bytes and the parallel u32 codepoint array
184,400; front-coded and interleaved they are 433,218.  That was 60% of the
whole loadable image.

Each entry carries its decoded name in a trailing comment, so the file stays
greppable and a regeneration still diffs readably.  Those comments cost source
bytes and no binary bytes.
"""
import sys
import unicodedata

CJK_PREFIX = "CJK UNIFIED IDEOGRAPH-"

# The C0/C1 control aliases, and the few figure/format ones.  NameAliases.txt
# is not shipped with a Python install, so the candidates are listed here and
# each is *verified* against unicodedata.lookup before it is emitted -- an
# entry that stops resolving disappears rather than going stale.
ALIAS_CANDIDATES = [
    # C0 and C1 control abbreviations
    "NUL", "SOH", "STX", "ETX", "EOT", "ENQ", "ACK", "BEL", "BS", "HT", "LF",
    "VT", "FF", "CR", "SO", "SI", "DLE", "DC1", "DC2", "DC3", "DC4", "NAK",
    "SYN", "ETB", "CAN", "EOM", "SUB", "ESC", "FS", "GS", "RS", "US", "SP",
    "DEL", "PAD", "HOP", "BPH", "NBH", "IND", "NEL", "SSA", "ESA", "HTS",
    "HTJ", "VTS", "PLD", "PLU", "RI", "SS2", "SS3", "DCS", "PU1", "PU2",
    "STS", "CCH", "MW", "SPA", "EPA", "SOS", "SGC", "SCI", "CSI", "ST",
    "OSC", "PM", "APC",
    # Control-character names
    "NULL", "BELL", "ALERT", "BACKSPACE", "CHARACTER TABULATION", "LINE FEED",
    "LINE TABULATION", "FORM FEED", "CARRIAGE RETURN", "NEXT LINE",
    "END OF MEDIUM", "SUBSTITUTE", "ESCAPE", "INDEX",
    # Format and space abbreviations
    "NBSP", "SHY", "ZWSP", "ZWNJ", "ZWJ", "LRM", "RLM", "LRE", "RLE", "PDF",
    "LRO", "RLO", "LRI", "RLI", "FSI", "PDI", "ALM", "BOM", "ZWNBSP",
    "NO-BREAK SPACE", "SOFT HYPHEN", "BYTE ORDER MARK",
    # The handful of documented corrections
    "PRESENTATION FORM FOR VERTICAL RIGHT WHITE LENTICULAR BRACKET",
    "LATIN CAPITAL LETTER GHA", "LATIN SMALL LETTER GHA",
    "WEIERSTRASS ELLIPTIC FUNCTION",
    "MICR ON US SYMBOL", "MICR DASH SYMBOL",
]

def collect():
    names = []
    cjk_ranges = []
    run_start = None
    for cp in range(0x110000):
        try:
            n = unicodedata.name(chr(cp))
        except ValueError:
            n = None
        is_cjk = n is not None and n.startswith(CJK_PREFIX)
        if is_cjk:
            if run_start is None:
                run_start = cp
        else:
            if run_start is not None:
                cjk_ranges.append((run_start, cp - 1))
                run_start = None
            if n is not None:
                names.append((n, cp))
    if run_start is not None:
        cjk_ranges.append((run_start, 0x10FFFF))

    have = {n for n, _ in names}
    for alias in ALIAS_CANDIDATES:
        if alias in have:
            continue
        try:
            ch = unicodedata.lookup(alias)
        except KeyError:
            continue
        if len(ch) != 1:
            continue
        have.add(alias)
        names.append((alias, ord(ch)))
    return names, cjk_ranges


UNINAME_MAX = 128           # must match UN_BUFSZ in src/compiler/uniname.asm


def emit(names, cjk_ranges, out):
    w = out.write
    longest = max(len(n) for n, _ in names)
    assert longest < UNINAME_MAX, (
        "a name of %d bytes does not fit uniname.asm's %d-byte decode buffer"
        % (longest, UNINAME_MAX))

    w(";; unicodename.asm - GENERATED by src/compiler/gen_unicodename.py.  Do not edit.\n")
    w(";;\n")
    w(";; The Unicode character names \\N{...} resolves, taken from the running\n")
    w(";; interpreter's own unicodedata (UCD %s).\n" % unicodedata.unidata_version)
    w(";;\n")
    w(";; uniname_blob is one stream, in codepoint order, of\n")
    w(";;\n")
    w(";;     db shared, db cpdelta [, dd cp when cpdelta == 255], db \"suffix\", 0\n")
    w(";;\n")
    w(";; where `shared` is the number of leading bytes this name has in common\n")
    w(";; with the PREVIOUS one.  uniname_lookup decodes into a %d-byte buffer as\n"
      % UNINAME_MAX)
    w(";; it scans, which costs nothing because the scan was already sequential.\n")
    w(";; Longest name here is %d bytes.\n" % longest)
    w(";;\n")
    w(";; The trailing comment on each line is the decoded name, so this file is\n")
    w(";; still greppable and a regeneration still diffs readably.\n")
    w(";;\n")
    w(";; CJK UNIFIED IDEOGRAPH-XXXX is not here -- 97046 names whose codepoint is\n")
    w(";; written in the name itself.  uniname_cjk_ranges is what makes a bogus one\n")
    w(";; still an error.\n")
    w("\n")
    # A data-only object still needs the marker, or the linker assumes an
    # executable stack for the whole program and says so.
    w("section .note.GNU-stack noalloc noexec nowrite progbits\n\n")
    w("section .rodata\n\n")

    w("global uniname_blob\n")
    w("uniname_blob:\n")
    prev_name, prev_cp, nbytes = "", 0, 0
    for n, cp in names:
        assert '"' not in n and "\\" not in n, n
        k = 0
        m = min(len(prev_name), len(n), 255)
        while k < m and prev_name[k] == n[k]:
            k += 1
        suffix = n[k:]
        d = cp - prev_cp
        tail = '"%s",0' % suffix if suffix else "0"
        if 0 <= d <= 254:
            line = "    db %d,%d,%s" % (k, d, tail)
            nbytes += 2 + len(suffix) + 1
        else:
            # The sequence jumps: an absolute codepoint follows the escape.
            line = "    db %d,255\n    dd 0x%X\n    db %s" % (k, cp, tail)
            nbytes += 6 + len(suffix) + 1
        w("%-52s ; %s\n" % (line, n))
        prev_name, prev_cp = n, cp
    w("global uniname_blob_end\n")
    w("uniname_blob_end:\n\n")

    w("align 4\n")
    w("global uniname_cjk_ranges\n")
    w("uniname_cjk_ranges:\n")
    for lo, hi in cjk_ranges:
        w("    dd 0x%X,0x%X\n" % (lo, hi))
    w("global uniname_cjk_ranges_end\n")
    w("uniname_cjk_ranges_end:\n")
    print(";; blob %d bytes for %d names" % (nbytes, len(names)), file=sys.stderr)


def main():
    names, cjk_ranges = collect()
    print(";; %d names, %d CJK ranges" % (len(names), len(cjk_ranges)),
          file=sys.stderr)
    emit(names, cjk_ranges, sys.stdout)


if __name__ == "__main__":
    main()
