#!/usr/bin/env python3
"""Regenerate src/compiler/unicodename.asm -- the table \\N{...} looks names up in.

    python3 src/compiler/gen_unicodename.py > src/compiler/unicodename.asm

The names come from the running interpreter's own `unicodedata`, the same way
gen_tables.py takes its opcode metadata from `opcode` and `dis`: transcribing
them by hand is how a table like this goes quietly out of date.

CJK UNIFIED IDEOGRAPH-XXXX is algorithmic and stays out of the table -- 97046
of the 143041 names, and the character's own codepoint is written in the name.
Only the ranges it is valid over are emitted, so a bogus one is still rejected.
Everything else, Hangul syllables included, is a literal entry.

The layout is deliberately the simplest thing that works: names NUL-separated
in one blob, codepoints in a parallel array, and a linear scan.  `\\N{...}` is
rare -- a handful of occurrences in a whole file -- so a scan of a megabyte
costs less than the index it would replace, in both code and source bytes.
"""
import sys
import unicodedata

CJK_PREFIX = "CJK UNIFIED IDEOGRAPH-"

# The C0/C1 control aliases, and the few figure/format ones.  NameAliases.txt
# is not shipped with a Python install, so the candidates are listed here and
# each is *verified* against unicodedata.lookup before it is emitted -- an
# entry that stops resolving disappears rather than going stale.
ALIAS_CANDIDATES = [
    # C0 and C1 control abbreviations
    "NUL", "SOH", "STX", "ETX", "EOT", "ENQ", "ACK", "BEL", "BS", "HT", "LF",
    "VT", "FF", "CR", "SO", "SI", "DLE", "DC1", "DC2", "DC3", "DC4", "NAK",
    "SYN", "ETB", "CAN", "EOM", "SUB", "ESC", "FS", "GS", "RS", "US", "SP",
    "DEL", "PAD", "HOP", "BPH", "NBH", "IND", "NEL", "SSA", "ESA", "HTS",
    "HTJ", "VTS", "PLD", "PLU", "RI", "SS2", "SS3", "DCS", "PU1", "PU2",
    "STS", "CCH", "MW", "SPA", "EPA", "SOS", "SGC", "SCI", "CSI", "ST",
    "OSC", "PM", "APC",
    # Control-character names
    "NULL", "BELL", "ALERT", "BACKSPACE", "CHARACTER TABULATION", "LINE FEED",
    "LINE TABULATION", "FORM FEED", "CARRIAGE RETURN", "NEXT LINE",
    "END OF MEDIUM", "SUBSTITUTE", "ESCAPE", "INDEX",
    # Format and space abbreviations
    "NBSP", "SHY", "ZWSP", "ZWNJ", "ZWJ", "LRM", "RLM", "LRE", "RLE", "PDF",
    "LRO", "RLO", "LRI", "RLI", "FSI", "PDI", "ALM", "BOM", "ZWNBSP",
    "NO-BREAK SPACE", "SOFT HYPHEN", "BYTE ORDER MARK",
    # The handful of documented corrections
    "PRESENTATION FORM FOR VERTICAL RIGHT WHITE LENTICULAR BRACKET",
    "LATIN CAPITAL LETTER GHA", "LATIN SMALL LETTER GHA",
    "WEIERSTRASS ELLIPTIC FUNCTION",
    "MICR ON US SYMBOL", "MICR DASH SYMBOL",
]

def collect():
    names = []
    cjk_ranges = []
    run_start = None
    for cp in range(0x110000):
        try:
            n = unicodedata.name(chr(cp))
        except ValueError:
            n = None
        is_cjk = n is not None and n.startswith(CJK_PREFIX)
        if is_cjk:
            if run_start is None:
                run_start = cp
        else:
            if run_start is not None:
                cjk_ranges.append((run_start, cp - 1))
                run_start = None
            if n is not None:
                names.append((n, cp))
    if run_start is not None:
        cjk_ranges.append((run_start, 0x10FFFF))

    have = {n for n, _ in names}
    for alias in ALIAS_CANDIDATES:
        if alias in have:
            continue
        try:
            ch = unicodedata.lookup(alias)
        except KeyError:
            continue
        if len(ch) != 1:
            continue
        have.add(alias)
        names.append((alias, ord(ch)))
    return names, cjk_ranges


def emit(names, cjk_ranges, out):
    w = out.write
    w(";; unicodename.asm - GENERATED by src/compiler/gen_unicodename.py.  Do not edit.\n")
    w(";;\n")
    w(";; The Unicode character names \\N{...} resolves, taken from the running\n")
    w(";; interpreter's own unicodedata (UCD %s).\n" % unicodedata.unidata_version)
    w(";;\n")
    w(";; uniname_blob holds every name, NUL-separated and in the order of\n")
    w(";; uniname_cp, which carries the codepoint each one names.  There is no\n")
    w(";; index: the lookup is a linear scan, because \\N{...} appears a handful of\n")
    w(";; times in a whole file and an index would cost more source than it saves.\n")
    w(";;\n")
    w(";; CJK UNIFIED IDEOGRAPH-XXXX is not here -- 97046 names whose codepoint is\n")
    w(";; written in the name itself.  uniname_cjk_ranges is what makes a bogus one\n")
    w(";; still an error.\n")
    w("\n")
    w("section .rodata\n\n")

    w("global uniname_blob\n")
    w("uniname_blob:\n")
    line, first = [], True
    for n, _ in names:
        assert '"' not in n and "\\" not in n, n
        line.append('"%s",0' % n)
        if sum(len(x) for x in line) > 160:
            w("    db " + ",".join(line) + "\n")
            line = []
    if line:
        w("    db " + ",".join(line) + "\n")
    w("global uniname_blob_end\n")
    w("uniname_blob_end:\n\n")

    w("align 4\n")
    w("global uniname_cp\n")
    w("uniname_cp:\n")
    vals = ["0x%X" % cp for _, cp in names]
    for i in range(0, len(vals), 16):
        w("    dd " + ",".join(vals[i:i + 16]) + "\n")
    w("\n")

    w("align 4\n")
    w("global uniname_cjk_ranges\n")
    w("uniname_cjk_ranges:\n")
    for lo, hi in cjk_ranges:
        w("    dd 0x%X,0x%X\n" % (lo, hi))
    w("global uniname_cjk_ranges_end\n")
    w("uniname_cjk_ranges_end:\n\n")

    w("section .data\n")
    w("align 8\n")
    w("global uniname_count\n")
    w("uniname_count: dq %d\n" % len(names))


def main():
    names, cjk_ranges = collect()
    print(";; %d names, %d CJK ranges" % (len(names), len(cjk_ranges)),
          file=sys.stderr)
    emit(names, cjk_ranges, sys.stdout)


if __name__ == "__main__":
    main()
