#!/usr/bin/env python3
"""Generate src/modules/ucd32_tables.asm -- the frozen Unicode 3.2 database.

`unicodedata.ucd_3_2_0` is a second, complete copy of the database at the
version RFC 3454 froze, and `stringprep` is written against it: an IDN label
has to fold the same way in 2026 as in 2002, so a property that moved since
must not move here.  CPython ships both copies for the same reason, and its
own `unicodedata` exposes the old one through this attribute.

The data comes from the running interpreter's `unicodedata.ucd_3_2_0`, which
is that very copy -- so this is a transcription of a transcription of nothing:
the two agree by construction, the way gen_unicodedata.py and
gen_unicodenorm.py do for the current version.

Only the properties something actually reads are emitted.  `stringprep` uses
category, bidirectional and normalize; `test_unicodedata` adds east_asian_width
and mirrored; combining and the decompositions are what normalize is built on.
The names (`lookup`/`name`) and the numeric values are not here: nothing asks
the 3.2 database for them, and each would be a second copy of a table larger
than all of these together.

Refuses to run on anything but CPython 3.12, for the reason gen_tables.py
gives: the outputs are committed, so a regeneration under a different version
would silently retable the interpreter.
"""
import sys
import unicodedata

if sys.implementation.name != "cpython" or sys.version_info[:2] != (3, 12):
    sys.exit("gen_ucd32.py must run on CPython 3.12")

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from gen_unicodenorm import build, emit_decomp, emit_raw, emit_comp, \
    emit_combining                                  # noqa: E402

MAX = 0x110000
UCD = unicodedata.ucd_3_2_0


def runs(fn):
    """One (start, value) row per place the property changes, as
    gen_unicodedata.py emits them: these tables are enormously runny and the
    lookup is the same binary search either way."""
    out = []
    prev = object()
    for cp in range(MAX):
        v = fn(chr(cp))
        if v != prev:
            out.append((cp, v))
            prev = v
    return out


def emit_string_pool(label, values):
    print("align 8")
    print("global %s_strings" % label)
    print("%s_strings:" % label)
    for i, _ in enumerate(values):
        print("    dq %s_s%d" % (label, i))
    for i, v in enumerate(values):
        print('%s_s%d: db "%s", 0' % (label, i, v))
    print()


def emit_runs(label, rows, values):
    index = {v: i for i, v in enumerate(values)}
    print(";; %s: %d runs over %d distinct values" % (label, len(rows), len(values)))
    print("align 8")
    print("global %s_starts" % label)
    print("%s_starts:" % label)
    for cp, v in rows:
        print("    dd 0x%06x, %d" % (cp, index[v]))
    print("global %s_count" % label)
    print("%s_count: dq %d" % (label, len(rows)))
    print()


def emit_int_runs(label, rows):
    print(";; %s: %d runs" % (label, len(rows)))
    print("align 8")
    print("global %s_starts" % label)
    print("%s_starts:" % label)
    for cp, v in rows:
        print("    dd 0x%06x, %d" % (cp, v))
    print("global %s_count" % label)
    print("%s_count: dq %d" % (label, len(rows)))
    print()


def main():
    print(";; ucd32_tables.asm - GENERATED by src/compiler/gen_ucd32.py.")
    print(";; Do not edit.  Unicode %s, from the running interpreter's own"
          % UCD.unidata_version)
    print(";; unicodedata.ucd_3_2_0 -- the frozen copy RFC 3454 is written")
    print(";; against and stringprep imports.")
    print(";;")
    print(";; The run tables have the same shape as unicodedataprops.asm's and")
    print(";; the decomposition tables the same shape as unicodenorm_tables'.")
    print(";; src/modules/ucd32.asm reads them through the same two lookups.")
    print()
    print('%include "macros.inc"')
    print()
    print("section .rodata")
    print()

    cat = runs(UCD.category)
    cat_vals = sorted({v for _, v in cat})
    emit_string_pool("ucd32_category", cat_vals)
    emit_runs("ucd32_category", cat, cat_vals)

    bidi = runs(UCD.bidirectional)
    bidi_vals = sorted({v for _, v in bidi})
    emit_string_pool("ucd32_bidi", bidi_vals)
    emit_runs("ucd32_bidi", bidi, bidi_vals)

    eaw = runs(UCD.east_asian_width)
    eaw_vals = sorted({v for _, v in eaw})
    emit_string_pool("ucd32_eaw", eaw_vals)
    emit_runs("ucd32_eaw", eaw, eaw_vals)

    emit_int_runs("ucd32_combining", runs(UCD.combining))
    emit_int_runs("ucd32_mirrored", runs(UCD.mirrored))

    canon, compat, comp, combining, raw = build(UCD)
    emit_decomp("ucd32", canon, compat)
    emit_raw("ucd32", raw)
    emit_comp("ucd32", comp)
    emit_combining("ucd32", combining)


if __name__ == "__main__":
    main()
