"""_ast -- the AST node classes.

GENERATED by src/compiler/gen_ast.py from CPython 3.12's own _ast.  Do not
edit; run `make regen`.  The half that builds these from apython's parser
is hand-written in _ast_build.py and imported at the bottom.

CPython's _ast is a C module and there is no Lib/_ast.py, so this cannot be
shadowed by a real stdlib on PYTHONPATH -- which is why it can be a plain
Python module rather than half of an assembly one, the way _io is.
"""

PyCF_ONLY_AST = 0x400
PyCF_TYPE_COMMENTS = 0x1000
PyCF_ALLOW_TOP_LEVEL_AWAIT = 0x2000


class AST:
    """The base of every node.

    CPython's constructor assigns positional arguments against _fields and
    then keyword arguments by name, accepting names that are in neither --
    the position attributes among them.  A field that was never assigned is
    an AttributeError on access rather than None, which is what
    ast.iter_fields and ast.dump both read it as.
    """

    __module__ = "ast"

    _fields = ()
    _attributes = ()

    def __init__(self, *args, **kwargs):
        fields = self._fields
        if len(args) > len(fields):
            raise TypeError(
                "%s constructor takes at most %d positional argument%s"
                % (type(self).__name__, len(fields),
                   "" if len(fields) == 1 else "s"))
        for name, value in zip(fields, args):
            setattr(self, name, value)
        for name, value in kwargs.items():
            setattr(self, name, value)

    def __repr__(self):
        parts = []
        for name in self._fields:
            try:
                parts.append("%s=%r" % (name, getattr(self, name)))
            except AttributeError:
                pass
        return "%s(%s)" % (type(self).__name__, ", ".join(parts))


class alias(AST):
    _fields = ('name', 'asname')
    _attributes = ('lineno', 'col_offset', 'end_lineno', 'end_col_offset')
    asname = None


class arg(AST):
    _fields = ('arg', 'annotation', 'type_comment')
    _attributes = ('lineno', 'col_offset', 'end_lineno', 'end_col_offset')
    annotation = None
    type_comment = None


class arguments(AST):
    _fields = ('posonlyargs', 'args', 'vararg', 'kwonlyargs', 'kw_defaults', 'kwarg', 'defaults')
    vararg = None
    kwarg = None


class boolop(AST):
    pass


class And(boolop):
    pass


class Or(boolop):
    pass


class cmpop(AST):
    pass


class Eq(cmpop):
    pass


class Gt(cmpop):
    pass


class GtE(cmpop):
    pass


class In(cmpop):
    pass


class Is(cmpop):
    pass


class IsNot(cmpop):
    pass


class Lt(cmpop):
    pass


class LtE(cmpop):
    pass


class NotEq(cmpop):
    pass


class NotIn(cmpop):
    pass


class comprehension(AST):
    _fields = ('target', 'iter', 'ifs', 'is_async')


class excepthandler(AST):
    _attributes = ('lineno', 'col_offset', 'end_lineno', 'end_col_offset')


class ExceptHandler(excepthandler):
    _fields = ('type', 'name', 'body')
    type = None
    name = None


class expr(AST):
    _attributes = ('lineno', 'col_offset', 'end_lineno', 'end_col_offset')


class Attribute(expr):
    _fields = ('value', 'attr', 'ctx')


class Await(expr):
    _fields = ('value',)


class BinOp(expr):
    _fields = ('left', 'op', 'right')


class BoolOp(expr):
    _fields = ('op', 'values')


class Call(expr):
    _fields = ('func', 'args', 'keywords')


class Compare(expr):
    _fields = ('left', 'ops', 'comparators')


class Constant(expr):
    _fields = ('value', 'kind')
    kind = None


class Dict(expr):
    _fields = ('keys', 'values')


class DictComp(expr):
    _fields = ('key', 'value', 'generators')


class FormattedValue(expr):
    _fields = ('value', 'conversion', 'format_spec')
    format_spec = None


class GeneratorExp(expr):
    _fields = ('elt', 'generators')


class IfExp(expr):
    _fields = ('test', 'body', 'orelse')


class JoinedStr(expr):
    _fields = ('values',)


class Lambda(expr):
    _fields = ('args', 'body')


class List(expr):
    _fields = ('elts', 'ctx')


class ListComp(expr):
    _fields = ('elt', 'generators')


class Name(expr):
    _fields = ('id', 'ctx')


class NamedExpr(expr):
    _fields = ('target', 'value')


class Set(expr):
    _fields = ('elts',)


class SetComp(expr):
    _fields = ('elt', 'generators')


class Slice(expr):
    _fields = ('lower', 'upper', 'step')
    lower = None
    upper = None
    step = None


class Starred(expr):
    _fields = ('value', 'ctx')


class Subscript(expr):
    _fields = ('value', 'slice', 'ctx')


class Tuple(expr):
    _fields = ('elts', 'ctx')


class UnaryOp(expr):
    _fields = ('op', 'operand')


class Yield(expr):
    _fields = ('value',)
    value = None


class YieldFrom(expr):
    _fields = ('value',)


class expr_context(AST):
    pass


class Del(expr_context):
    pass


class Load(expr_context):
    pass


class Store(expr_context):
    pass


class keyword(AST):
    _fields = ('arg', 'value')
    _attributes = ('lineno', 'col_offset', 'end_lineno', 'end_col_offset')
    arg = None


class match_case(AST):
    _fields = ('pattern', 'guard', 'body')
    guard = None


class mod(AST):
    pass


class Expression(mod):
    _fields = ('body',)


class FunctionType(mod):
    _fields = ('argtypes', 'returns')


class Interactive(mod):
    _fields = ('body',)


class Module(mod):
    _fields = ('body', 'type_ignores')


class operator(AST):
    pass


class Add(operator):
    pass


class BitAnd(operator):
    pass


class BitOr(operator):
    pass


class BitXor(operator):
    pass


class Div(operator):
    pass


class FloorDiv(operator):
    pass


class LShift(operator):
    pass


class MatMult(operator):
    pass


class Mod(operator):
    pass


class Mult(operator):
    pass


class Pow(operator):
    pass


class RShift(operator):
    pass


class Sub(operator):
    pass


class pattern(AST):
    _attributes = ('lineno', 'col_offset', 'end_lineno', 'end_col_offset')


class MatchAs(pattern):
    _fields = ('pattern', 'name')
    pattern = None
    name = None


class MatchClass(pattern):
    _fields = ('cls', 'patterns', 'kwd_attrs', 'kwd_patterns')


class MatchMapping(pattern):
    _fields = ('keys', 'patterns', 'rest')
    rest = None


class MatchOr(pattern):
    _fields = ('patterns',)


class MatchSequence(pattern):
    _fields = ('patterns',)


class MatchSingleton(pattern):
    _fields = ('value',)


class MatchStar(pattern):
    _fields = ('name',)
    name = None


class MatchValue(pattern):
    _fields = ('value',)


class stmt(AST):
    _attributes = ('lineno', 'col_offset', 'end_lineno', 'end_col_offset')


class AnnAssign(stmt):
    _fields = ('target', 'annotation', 'value', 'simple')
    value = None


class Assert(stmt):
    _fields = ('test', 'msg')
    msg = None


class Assign(stmt):
    _fields = ('targets', 'value', 'type_comment')
    type_comment = None


class AsyncFor(stmt):
    _fields = ('target', 'iter', 'body', 'orelse', 'type_comment')
    type_comment = None


class AsyncFunctionDef(stmt):
    _fields = ('name', 'args', 'body', 'decorator_list', 'returns', 'type_comment', 'type_params')
    returns = None
    type_comment = None


class AsyncWith(stmt):
    _fields = ('items', 'body', 'type_comment')
    type_comment = None


class AugAssign(stmt):
    _fields = ('target', 'op', 'value')


class Break(stmt):
    pass


class ClassDef(stmt):
    _fields = ('name', 'bases', 'keywords', 'body', 'decorator_list', 'type_params')


class Continue(stmt):
    pass


class Delete(stmt):
    _fields = ('targets',)


class Expr(stmt):
    _fields = ('value',)


class For(stmt):
    _fields = ('target', 'iter', 'body', 'orelse', 'type_comment')
    type_comment = None


class FunctionDef(stmt):
    _fields = ('name', 'args', 'body', 'decorator_list', 'returns', 'type_comment', 'type_params')
    returns = None
    type_comment = None


class Global(stmt):
    _fields = ('names',)


class If(stmt):
    _fields = ('test', 'body', 'orelse')


class Import(stmt):
    _fields = ('names',)


class ImportFrom(stmt):
    _fields = ('module', 'names', 'level')
    module = None
    level = None


class Match(stmt):
    _fields = ('subject', 'cases')


class Nonlocal(stmt):
    _fields = ('names',)


class Pass(stmt):
    pass


class Raise(stmt):
    _fields = ('exc', 'cause')
    exc = None
    cause = None


class Return(stmt):
    _fields = ('value',)
    value = None


class Try(stmt):
    _fields = ('body', 'handlers', 'orelse', 'finalbody')


class TryStar(stmt):
    _fields = ('body', 'handlers', 'orelse', 'finalbody')


class TypeAlias(stmt):
    _fields = ('name', 'type_params', 'value')


class While(stmt):
    _fields = ('test', 'body', 'orelse')


class With(stmt):
    _fields = ('items', 'body', 'type_comment')
    type_comment = None


class type_ignore(AST):
    pass


class TypeIgnore(type_ignore):
    _fields = ('lineno', 'tag')


class type_param(AST):
    _attributes = ('lineno', 'col_offset', 'end_lineno', 'end_col_offset')


class ParamSpec(type_param):
    _fields = ('name',)


class TypeVar(type_param):
    _fields = ('name', 'bound')
    bound = None


class TypeVarTuple(type_param):
    _fields = ('name',)


class unaryop(AST):
    pass


class Invert(unaryop):
    pass


class Not(unaryop):
    pass


class UAdd(unaryop):
    pass


class USub(unaryop):
    pass


class withitem(AST):
    _fields = ('context_expr', 'optional_vars')
    optional_vars = None


# The bridge to apython's parser: compile(..., PyCF_ONLY_AST) calls
# _from_raw on the raw tuple tree the assembly walker hands back.
from _ast_build import _from_raw  # noqa: E402,F401
