; dtoa.asm - the shortest decimal that reads back as a given double
;
; float_repr used to find this by trying "%.1e" through "%.17e", each twice --
; as rendered, and with the last digit carried up by one -- and calling strtod
; after every attempt to see whether it read back.  That is up to 34 snprintf
; and 34 strtod calls per repr(), all of them through glibc's
; arbitrary-precision printf_fp, and the cost is LINEAR IN THE DIGIT COUNT:
; repr(0.1) exits at the first precision and repr(3.141592653589793) walks all
; the way to sixteen.  It measured 0.09x of CPython on a repr-heavy loop, where
; CPython's dtoa is flat.
;
; This computes the answer directly, in Ryu's formulation.  The shortest
; decimal that round-trips is the shortest one lying inside the interval of
; reals that round to this double, so the work is: scale that interval's low,
; mid and high bounds into decimal by multiplying by a power of five, then
; strip digits while the interval still contains a choice.  Each multiply is
; one 64x128 -> high 64, which is two `mul` instructions and an add against a
; table generated by src/gen_dtoa.py.
;
; The algorithm was written and validated in Python before any of this was
; written: 67,919 doubles -- all 2098 powers of two, the subnormal boundary,
; 60,000 random bit patterns and every value the old search was known to get
; wrong -- diffed against CPython's repr with zero mismatches.
; tests/test_float_format_diff.py is the standing gate over the same shape of
; corpus, and tests/test_float_repr_ties.py independently checks minimality.
;
; Nothing is copied from Ryu's own sources: the tables are derived from the
; definition of the powers by the generator, and what is transcribed is the
; construction, not an implementation.

%include "macros.inc"
%include "object.inc"

extern dtoa_pow5_split
extern dtoa_pow5_inv_split

DTOA_POW5_BITS     equ 125
DTOA_POW5_INV_BITS equ 125

; v/10 is mulhi(v, this) >> 3 for every u64.  The strip loop below runs once
; per digit removed and does three of these, against a `div r64` of thirty-odd
; cycles each.
DIV10_MAGIC equ 0xCCCCCCCCCCCCCCCD

;; ============================================================================
;; DIV10 quotient, scratch -- %1 <- %1 / 10.  Clobbers rax, rdx and %2.
;; ============================================================================
%macro DIV10 2
    mov rax, %1
    mov %2, DIV10_MAGIC
    mul %2
    shr rdx, 3
    mov %1, rdx
%endmacro

section .text

;; ============================================================================
;; dtoa_mulshift(rdi = m, rsi = a 128-bit table entry, edx = j) -> rax
;;
;; (m * entry) >> j, where the entry is stored low qword first and j is
;; between 64 and 127.
;;
;; The full product is 192 bits and only its top is wanted, so the low half of
;; m*lo is dropped: what is kept is (m*lo >> 64) + m*hi, shifted right by
;; j-64.  Ryu's bound is that the answer fits in 64 bits for every input a
;; double can produce, which is why the high half of that sum only feeds the
;; shift and is never returned.
;; ============================================================================
DEF_FUNC_BARE dtoa_mulshift
    mov ecx, edx
    sub ecx, 64                     ; the shift, 0..63
    mov r8, [rsi]                   ; the entry's low qword
    mov r9, [rsi + 8]               ; and its high
    mov rax, rdi
    mul r8                          ; rdx:rax = m * lo
    mov r10, rdx                    ; only the high half survives
    mov rax, rdi
    mul r9                          ; rdx:rax = m * hi
    add rax, r10
    adc rdx, 0
    shrd rax, rdx, cl               ; the low 64 of (rdx:rax) >> cl
    ret
END_FUNC dtoa_mulshift

;; ============================================================================
;; dtoa_pow5factor(rdi = v) -> eax = how many times 5 divides v
;;
;; Only reached on the rare trailing-zero arms, where q <= 21, so the loop is
;; short and a plain division is the right shape.
;; ============================================================================
DEF_FUNC_BARE dtoa_pow5factor
    xor r8d, r8d
    test rdi, rdi
    jz .pf_done
.pf_loop:
    mov rax, rdi
    xor edx, edx
    mov r9d, 5
    div r9                          ; rax = v/5, rdx = v%5
    test rdx, rdx
    jnz .pf_done
    mov rdi, rax
    inc r8d
    jmp .pf_loop
.pf_done:
    mov eax, r8d
    ret
END_FUNC dtoa_pow5factor

;; ============================================================================
;; dtoa_shortest(rdi = the raw bits of a finite, non-zero double)
;;   -> rax = the decimal digits as an integer, edx = the decimal exponent
;;
;; The magnitude of the double is exactly rax * 10^edx, with rax carrying as
;; few digits as any decimal that reads back as this double.  The sign is the
;; caller's business: it is one bit of the input and does not affect any of
;; the arithmetic here.
;;
;; Zero, the infinities and the NaNs are the caller's business too -- they
;; have no shortest decimal and the bound arithmetic below does not apply to
;; them.
;; ============================================================================
DT_E10      equ 8
DT_M2       equ 16
DT_MMSHIFT  equ 24
DT_ACCEPT   equ 32              ; accept_bounds: the interval is closed
DT_VMTZ     equ 40              ; vm is known to have trailing zeros
DT_VRTZ     equ 48              ; vr is known to have trailing zeros
DT_LASTDIG  equ 56              ; the digit the strip loop last discarded
DT_IEEE_M   equ 64
DT_IEEE_E   equ 72
DT_ENTRY    equ 80              ; the table entry the three bounds share
DT_SHIFT    equ 88              ; and the shift they share
DT_Q        equ 96              ; q, across dtoa_bounds -- which calls
                                ; dtoa_mulshift, and that uses r10 as scratch
DT_FRAME    equ 120             ; 120 + 5 pushes keeps rsp 16-aligned

DEF_FUNC dtoa_shortest, DT_FRAME
    push rbx
    push r12
    push r13
    push r14
    push r15

    ; --- decode ------------------------------------------------------------
    mov rbx, rdi
    mov rax, rbx
    mov rcx, (1 << 52) - 1
    and rax, rcx
    mov [rbp - DT_IEEE_M], rax          ; ieee_mantissa
    mov rcx, rbx
    shr rcx, 52
    and ecx, 0x7FF
    mov [rbp - DT_IEEE_E], rcx          ; ieee_exponent

    test ecx, ecx
    jnz .ds_normal
    ; A subnormal has no implicit leading one, and its exponent is the same as
    ; the smallest normal's.
    mov r15d, 1 - 1023 - 52 - 2
    mov rbx, rax
    jmp .ds_decoded
.ds_normal:
    lea r15d, [rcx - (1023 + 52 + 2)]
    mov rbx, rax
    bts rbx, 52
.ds_decoded:
    mov [rbp - DT_M2], rbx              ; m2, and r15d = e2

    ; The interval is closed when the mantissa is even, which is the rule that
    ; makes a tie resolve to the same double the reader will produce.
    xor eax, eax
    test bl, 1
    setz al
    mov [rbp - DT_ACCEPT], rax

    ; The low bound is one half-ulp below unless this is the smallest value of
    ; its binade, where the gap below is half the gap above.
    mov eax, 1
    cmp qword [rbp - DT_IEEE_M], 0
    jne .ds_mm
    cmp qword [rbp - DT_IEEE_E], 1
    jbe .ds_mm
    xor eax, eax
.ds_mm:
    mov [rbp - DT_MMSHIFT], rax

    mov qword [rbp - DT_VMTZ], 0
    mov qword [rbp - DT_VRTZ], 0
    mov qword [rbp - DT_LASTDIG], 0

    cmp r15d, 0
    jl .ds_neg_e2

    ; --- e2 >= 0: divide by a power of ten, i.e. multiply by its reciprocal --
    mov eax, r15d
    imul eax, eax, 78913
    shr eax, 18                         ; floor(log10(2^e2))
    cmp r15d, 3
    jle .ds_pq
    dec eax
.ds_pq:
    mov r10d, eax                       ; q
    mov [rbp - DT_E10], eax             ; e10 = q
    mov [rbp - DT_Q], eax

    mov ecx, eax
    imul ecx, ecx, 1217359
    shr ecx, 19
    inc ecx                             ; pow5bits(q)
    add ecx, DTOA_POW5_INV_BITS - 1     ; k
    mov edx, r10d
    sub edx, r15d
    add edx, ecx                        ; i = -e2 + q + k
    mov [rbp - DT_SHIFT], rdx

    lea rsi, [rel dtoa_pow5_inv_split]
    mov eax, r10d
    shl rax, 4
    add rsi, rax
    mov [rbp - DT_ENTRY], rsi

    call dtoa_bounds                    ; r12 = vr, r13 = vp, r14 = vm

    mov r10d, [rbp - DT_Q]              ; r10 did not survive the call
    cmp r10d, 21
    jg .ds_strip
    ; Below 5^22 the bounds can be exactly representable, and then a digit
    ; stripped off them was a real zero rather than a rounding artefact.
    mov rax, [rbp - DT_M2]
    shl rax, 2                          ; mv
    xor edx, edx
    mov r9d, 5
    push rax
    div r9
    pop rax
    test rdx, rdx
    jnz .ds_pos_not_mv
    mov rdi, [rbp - DT_M2]
    shl rdi, 2                          ; mv
    call dtoa_pow5factor
    cmp eax, r10d
    setae al
    movzx eax, al
    mov [rbp - DT_VRTZ], rax
    jmp .ds_strip
.ds_pos_not_mv:
    cmp qword [rbp - DT_ACCEPT], 0
    je .ds_pos_vp
    call dtoa_mm_value                  ; rax = 4*m2 - 1 - mm_shift
    mov rdi, rax
    call dtoa_pow5factor
    cmp eax, r10d
    setae al
    movzx eax, al
    mov [rbp - DT_VMTZ], rax
    jmp .ds_strip
.ds_pos_vp:
    mov rdi, [rbp - DT_M2]
    shl rdi, 2
    add rdi, 2
    call dtoa_pow5factor
    cmp eax, r10d
    jb .ds_strip
    dec r13                             ; vp is exact, so the bound is open
    jmp .ds_strip

    ; --- e2 < 0: multiply by a power of five --------------------------------
.ds_neg_e2:
    mov eax, r15d
    neg eax                             ; -e2
    mov r11d, eax
    imul eax, eax, 732923
    shr eax, 20                         ; floor(log10(5^-e2))
    cmp r11d, 1
    jle .ds_nq
    dec eax
.ds_nq:
    mov r10d, eax                       ; q
    mov [rbp - DT_Q], eax
    add eax, r15d
    mov [rbp - DT_E10], eax             ; e10 = q + e2

    mov edx, r11d
    sub edx, r10d                       ; i = -e2 - q
    mov r8d, edx

    mov ecx, edx
    imul ecx, ecx, 1217359
    shr ecx, 19
    inc ecx                             ; pow5bits(i)
    sub ecx, DTOA_POW5_BITS             ; k
    mov edx, r10d
    sub edx, ecx                        ; j = q - k
    mov [rbp - DT_SHIFT], rdx

    lea rsi, [rel dtoa_pow5_split]
    mov eax, r8d
    shl rax, 4
    add rsi, rax
    mov [rbp - DT_ENTRY], rsi

    call dtoa_bounds

    mov r10d, [rbp - DT_Q]              ; r10 did not survive the call
    cmp r10d, 1
    jg .ds_neg_q_big
    ; Every bound is an integer here, so vr's trailing zeros are real.
    mov qword [rbp - DT_VRTZ], 1
    cmp qword [rbp - DT_ACCEPT], 0
    je .ds_neg_vp
    mov rax, [rbp - DT_MMSHIFT]
    mov [rbp - DT_VMTZ], rax
    jmp .ds_strip
.ds_neg_vp:
    dec r13
    jmp .ds_strip
.ds_neg_q_big:
    cmp r10d, 63
    jae .ds_strip
    ; vr's low q bits are zero exactly when mv is a multiple of 2^q.
    mov rax, [rbp - DT_M2]
    shl rax, 2
    mov ecx, r10d
    mov rdx, 1
    shl rdx, cl
    dec rdx
    test rax, rdx
    jnz .ds_strip
    mov qword [rbp - DT_VRTZ], 1

    ; --- strip digits while the interval still holds a choice ---------------
.ds_strip:
    mov qword [rbp - DT_LASTDIG], 0
    mov rax, [rbp - DT_VMTZ]
    or rax, [rbp - DT_VRTZ]
    jnz .ds_strip_exact

    ; The common arm: no bound is known exact, so a plain loop.
.ds_gen_loop:
    mov r8, r13
    DIV10 r8, r9                        ; vp/10
    mov r11, r14
    DIV10 r11, r9                       ; vm/10
    cmp r8, r11
    jbe .ds_gen_done
    mov r15, r12
    DIV10 r15, r9                       ; vr/10
    mov rax, r15
    lea rax, [rax + rax*4]
    add rax, rax
    mov rcx, r12
    sub rcx, rax                        ; vr % 10
    mov [rbp - DT_LASTDIG], rcx
    mov r12, r15
    mov r13, r8
    mov r14, r11
    inc dword [rbp - DT_E10]
    jmp .ds_gen_loop
.ds_gen_done:
    ; Round up when the low bound is the only choice left, or when the digit
    ; that was dropped says to.
    xor eax, eax
    cmp r12, r14
    sete al
    cmp qword [rbp - DT_LASTDIG], 5
    setae cl
    or al, cl
    movzx rax, al
    add rax, r12
    mov edx, [rbp - DT_E10]
    jmp .ds_out

    ; The rare arm: a bound is exactly representable, so a stripped zero has
    ; to be distinguished from a rounded one.
.ds_strip_exact:
.ds_ex_loop:
    mov r8, r13
    DIV10 r8, r9
    mov r11, r14
    DIV10 r11, r9
    cmp r8, r11
    jbe .ds_ex_done
    ; vm keeps its exactness only while the digit it loses is a zero.
    ; DIV10 clobbers rax, so vm is re-read from r14 after it, not before.
    mov r15, r14
    DIV10 r15, r9                       ; vm/10
    mov rcx, r15
    lea rcx, [rcx + rcx*4]
    add rcx, rcx                        ; 10*(vm/10)
    mov rax, r14
    sub rax, rcx                        ; vm % 10
    jz .ds_ex_vm_ok
    mov qword [rbp - DT_VMTZ], 0
.ds_ex_vm_ok:
    cmp qword [rbp - DT_LASTDIG], 0
    je .ds_ex_vr_ok
    mov qword [rbp - DT_VRTZ], 0
.ds_ex_vr_ok:
    mov r15, r12
    DIV10 r15, r9
    mov rax, r15
    lea rax, [rax + rax*4]
    add rax, rax
    mov rcx, r12
    sub rcx, rax
    mov [rbp - DT_LASTDIG], rcx
    mov r12, r15
    mov r13, r8
    mov r14, r11
    inc dword [rbp - DT_E10]
    jmp .ds_ex_loop
.ds_ex_done:
    cmp qword [rbp - DT_VMTZ], 0
    je .ds_ex_tail
.ds_ex_vm_loop:
    mov r15, r14
    DIV10 r15, r9                       ; vm/10
    mov rcx, r15
    lea rcx, [rcx + rcx*4]
    add rcx, rcx
    mov rax, r14                        ; after DIV10, which clobbers rax
    sub rax, rcx
    jnz .ds_ex_tail                     ; vm has no more trailing zeros
    cmp qword [rbp - DT_LASTDIG], 0
    je .ds_ex_vm2
    mov qword [rbp - DT_VRTZ], 0
.ds_ex_vm2:
    mov r8, r13
    DIV10 r8, r9
    mov r11, r12
    DIV10 r11, r9
    mov rax, r11
    lea rax, [rax + rax*4]
    add rax, rax
    mov rcx, r12
    sub rcx, rax
    mov [rbp - DT_LASTDIG], rcx
    mov r12, r11
    mov r13, r8
    mov r14, r15
    inc dword [rbp - DT_E10]
    jmp .ds_ex_vm_loop
.ds_ex_tail:
    ; An exact half, with an even value below it, rounds down -- the same
    ; round-half-to-even the reader will apply.
    cmp qword [rbp - DT_VRTZ], 0
    je .ds_ex_round
    cmp qword [rbp - DT_LASTDIG], 5
    jne .ds_ex_round
    test r12b, 1
    jnz .ds_ex_round
    mov qword [rbp - DT_LASTDIG], 4
.ds_ex_round:
    xor eax, eax
    cmp r12, r14
    jne .ds_ex_cmp_dig
    ; vr has reached the low bound.  Rounding up is right unless the bound is
    ; both exact and included, in which case the bound itself is the answer.
    mov rcx, [rbp - DT_VMTZ]
    and rcx, [rbp - DT_ACCEPT]
    test rcx, rcx
    jnz .ds_ex_cmp_dig
    mov eax, 1
.ds_ex_cmp_dig:
    cmp qword [rbp - DT_LASTDIG], 5
    setae cl
    or al, cl
    movzx rax, al
    add rax, r12
    mov edx, [rbp - DT_E10]

.ds_out:
    pop r15
    pop r14
    pop r13
    pop r12
    pop rbx
    leave
    ret
END_FUNC dtoa_shortest

;; ============================================================================
;; dtoa_mm_value() -> rax = 4*m2 - 1 - mm_shift
;;
;; The low bound's numerator, read out of dtoa_shortest's frame.  Only called
;; from there, and only from the arms that need it twice.
;; ============================================================================
DEF_FUNC_BARE dtoa_mm_value
    mov rax, [rbp - DT_M2]
    shl rax, 2
    sub rax, 1
    sub rax, [rbp - DT_MMSHIFT]
    ret
END_FUNC dtoa_mm_value

;; ============================================================================
;; dtoa_bounds() -> r12 = vr, r13 = vp, r14 = vm
;;
;; Scale the double's mid, high and low bounds by the table entry
;; dtoa_shortest parked in its frame.  Split out because both exponent arms
;; do exactly this and differ only in which table they picked.
;; ============================================================================
DEF_FUNC_BARE dtoa_bounds
    push rbx
    mov rbx, [rbp - DT_M2]

    mov rdi, rbx
    shl rdi, 2
    mov rsi, [rbp - DT_ENTRY]
    mov edx, [rbp - DT_SHIFT]
    call dtoa_mulshift
    mov r12, rax

    mov rdi, rbx
    shl rdi, 2
    add rdi, 2
    mov rsi, [rbp - DT_ENTRY]
    mov edx, [rbp - DT_SHIFT]
    call dtoa_mulshift
    mov r13, rax

    mov rdi, rbx
    shl rdi, 2
    sub rdi, 1
    sub rdi, [rbp - DT_MMSHIFT]
    mov rsi, [rbp - DT_ENTRY]
    mov edx, [rbp - DT_SHIFT]
    call dtoa_mulshift
    mov r14, rax

    pop rbx
    ret
END_FUNC dtoa_bounds

;; ============================================================================
;; dtoa_format(rdi = digits, esi = exp10, edx = negative?, rcx = out buffer)
;;   -> rax = the number of bytes written
;;
;; Render digits * 10^exp10 the way repr() does, into a caller's buffer of at
;; least 32 bytes.  The notation rule is CPython's and not %g's: fixed when the
;; decimal exponent of the leading digit is in [-4, 16), exponential otherwise.
;; %g goes exponential as soon as the exponent reaches the precision, which is
;; how repr(100.0) once came out as "1e+02".
;;
;; A fixed rendering always carries a point -- "100.0", not "100" -- and an
;; exponential one carries one only when there is more than one digit, so it is
;; "1e+16" rather than "1.0e+16".  The exponent is at least two digits.
;; ============================================================================
DF_DIGITS  equ 8
DF_EXP10   equ 16
DF_NEG     equ 24
DF_OUT     equ 32
DF_NDIG    equ 40
DF_SCRATCH equ 72               ; 24 bytes of reversed digits
DF_FRAME   equ 96               ; 96 + 2 pushes keeps rsp 16-aligned

DEF_FUNC dtoa_format, DF_FRAME
    push rbx
    push r12

    mov [rbp - DF_DIGITS], rdi
    mov [rbp - DF_EXP10], rsi
    mov [rbp - DF_NEG], rdx
    mov [rbp - DF_OUT], rcx

    ; --- the digits, least significant first into the scratch ---------------
    lea rbx, [rbp - DF_SCRATCH]
    xor r12d, r12d                      ; count
    mov rax, rdi
    test rax, rax
    jnz .df_digits
    mov byte [rbx], '0'
    mov r12d, 1
    jmp .df_have_digits
.df_digits:
    mov r8, DIV10_MAGIC
.df_dig_loop:
    test rax, rax
    jz .df_have_digits
    mov r9, rax
    mul r8
    shr rdx, 3                          ; rdx = v/10
    mov rax, rdx
    lea rcx, [rdx + rdx*4]
    add rcx, rcx                        ; (v/10)*10
    sub r9, rcx                         ; v % 10
    add r9b, '0'
    mov [rbx + r12], r9b
    inc r12
    jmp .df_dig_loop
.df_have_digits:
    mov [rbp - DF_NDIG], r12

    ; dec_exp = exp10 + ndigits - 1
    mov rax, [rbp - DF_EXP10]
    add rax, r12
    dec rax
    mov r11, rax                        ; r11 = dec_exp

    mov rdi, [rbp - DF_OUT]
    cmp qword [rbp - DF_NEG], 0
    je .df_no_sign
    mov byte [rdi], '-'
    inc rdi
.df_no_sign:

    cmp r11, -4
    jl .df_sci
    cmp r11, 16
    jge .df_sci

    ; --- fixed ------------------------------------------------------------
    mov rsi, [rbp - DF_EXP10]
    test rsi, rsi
    js .df_fixed_frac

    ; exp10 >= 0: every digit is integral, then padding zeros, then ".0"
    call df_emit_digits                 ; rdi advances past them
.df_pad:
    test rsi, rsi
    jz .df_pad_done
    mov byte [rdi], '0'
    inc rdi
    dec rsi
    jmp .df_pad
.df_pad_done:
    mov word [rdi], '.0'                ; two bytes, '.' then '0'
    add rdi, 2
    jmp .df_done

.df_fixed_frac:
    ; split = ndigits + exp10; positive means the point falls inside the digits
    mov rdx, [rbp - DF_NDIG]
    add rdx, rsi                        ; split
    test rdx, rdx
    jle .df_leading_zeros

    mov r10, rdx                        ; how many digits before the point
    call df_emit_n                      ; emits r10 of them
    mov byte [rdi], '.'
    inc rdi
    mov r10, [rbp - DF_NDIG]
    sub r10, rdx                        ; the rest
    call df_emit_rest
    jmp .df_done

.df_leading_zeros:
    mov word [rdi], '0.'
    add rdi, 2
    neg rdx                             ; how many zeros after the point
.df_lz_loop:
    test rdx, rdx
    jz .df_lz_done
    mov byte [rdi], '0'
    inc rdi
    dec rdx
    jmp .df_lz_loop
.df_lz_done:
    call df_emit_digits
    jmp .df_done

    ; --- exponential -------------------------------------------------------
.df_sci:
    ; the leading digit, then a point and the rest only if there is a rest
    mov r10, 1
    call df_emit_n
    cmp qword [rbp - DF_NDIG], 1
    jbe .df_sci_e
    mov byte [rdi], '.'
    inc rdi
    mov r10, [rbp - DF_NDIG]
    dec r10
    call df_emit_rest
.df_sci_e:
    mov byte [rdi], 'e'
    inc rdi
    test r11, r11
    jns .df_exp_pos
    mov byte [rdi], '-'
    neg r11
    jmp .df_exp_sign_done
.df_exp_pos:
    mov byte [rdi], '+'
.df_exp_sign_done:
    inc rdi

    ; at least two digits
    mov rax, r11
    mov r8, DIV10_MAGIC
    lea rbx, [rbp - DF_SCRATCH]
    xor r12d, r12d
.df_exp_loop:
    test rax, rax
    jz .df_exp_have
    mov r9, rax
    mul r8
    shr rdx, 3
    mov rax, rdx
    lea rcx, [rdx + rdx*4]
    add rcx, rcx
    sub r9, rcx
    add r9b, '0'
    mov [rbx + r12], r9b
    inc r12
    jmp .df_exp_loop
.df_exp_have:
    cmp r12, 2
    jae .df_exp_emit
    mov byte [rbx + r12], '0'
    inc r12
    jmp .df_exp_have
.df_exp_emit:
    test r12, r12
    jz .df_done
    dec r12
    mov al, [rbx + r12]
    mov [rdi], al
    inc rdi
    jmp .df_exp_emit

.df_done:
    mov byte [rdi], 0
    sub rdi, [rbp - DF_OUT]
    mov rax, rdi
    pop r12
    pop rbx
    leave
    ret
END_FUNC dtoa_format

;; ============================================================================
;; df_emit_digits() -> rdi advanced
;;
;; Write every digit, most significant first, out of the reversed scratch.
;; Reads dtoa_format's frame through rbp and is only callable from it.
;; ============================================================================
DEF_FUNC_BARE df_emit_digits
    mov r10, [rbp - DF_NDIG]
    ; fall through
END_FUNC df_emit_digits

;; ============================================================================
;; df_emit_n() -> rdi advanced
;;
;; The first r10 digits, most significant first.
;; ============================================================================
DEF_FUNC_BARE df_emit_n
    lea rbx, [rbp - DF_SCRATCH]
    mov rcx, [rbp - DF_NDIG]
.den_loop:
    test r10, r10
    jz .den_done
    dec rcx
    mov al, [rbx + rcx]
    mov [rdi], al
    inc rdi
    dec r10
    jmp .den_loop
.den_done:
    ret
END_FUNC df_emit_n

;; ============================================================================
;; df_emit_rest() -> rdi advanced
;;
;; The LAST r10 digits, most significant first -- what follows the point.
;; ============================================================================
DEF_FUNC_BARE df_emit_rest
    lea rbx, [rbp - DF_SCRATCH]
    mov rcx, r10
.der_loop:
    test rcx, rcx
    jz .der_done
    dec rcx
    mov al, [rbx + rcx]
    mov [rdi], al
    inc rdi
    jmp .der_loop
.der_done:
    ret
END_FUNC df_emit_rest
