#!/usr/bin/env python3
"""Regenerate src/dtoa_tables.asm -- the powers of five Ryu multiplies by.

Run through `make regen`.  The output is committed, so building never needs
Python; this exists so the tables can be checked by regenerating them rather
than read.

Nothing here is transcribed from a reference implementation.  Both tables are
derived arithmetically from the definition, in exact Python integers:

    POW5_SPLIT[i]     = floor(5^i / 2^(ceil(log2(5^i)) - 125))
    POW5_INV_SPLIT[q] = floor(2^(bitlen(5^q) - 1 + 125) / 5^q) + 1

which is to say: 5^i and its reciprocal, each normalised to 125 significant
bits so that a 64x128 multiply-and-shift lands the result in one register.
The +1 on the reciprocal is what makes the truncated division round the right
way for every input; Ryu's own tables are the same numbers for the same
reason.

The ranges come from the exponents a finite double can have:
  - e2 >= 0 reaches q = log10(2^e2) up to 290
  - e2 <  0 reaches i = -e2 - log10(5^-e2) up to 325
Both are computed here rather than pasted, and the generator asserts that the
entries fit in 128 bits.
"""

import sys

POW5_BITCOUNT = 125
POW5_INV_BITCOUNT = 125
POW5_INV_MAX_Q = 290
POW5_MAX_I = 325


def compute_pow5(i):
    p = 5 ** i
    shift = p.bit_length() - POW5_BITCOUNT
    return p >> shift if shift > 0 else p << -shift


def compute_inv_pow5(q):
    p = 5 ** q
    j = p.bit_length() - 1 + POW5_INV_BITCOUNT
    return (1 << j) // p + 1


def emit(fh, name, values, comment):
    fh.write("\n;; %s\n" % comment)
    fh.write("align 16\n")
    fh.write("global %s\n%s:\n" % (name, name))
    for n, v in enumerate(values):
        assert 0 <= v < (1 << 128), (name, n, v.bit_length())
        lo = v & 0xFFFFFFFFFFFFFFFF
        hi = v >> 64
        fh.write("    dq 0x%016x, 0x%016x    ; %d\n" % (lo, hi, n))


def main():
    out = "src/dtoa_tables.asm"
    with open(out, "w") as fh:
        fh.write("; dtoa_tables.asm - GENERATED by src/gen_dtoa.py; do not edit.\n")
        fh.write(";\n")
        fh.write("; The powers of five Ryu's shortest-round-trip conversion multiplies\n")
        fh.write("; by, each normalised to %d significant bits and stored as a 128-bit\n"
                 % POW5_BITCOUNT)
        fh.write("; value, low qword first.  Regenerate with `make regen`.\n")
        fh.write("\nsection .rodata\n")
        emit(fh, "dtoa_pow5_split",
             [compute_pow5(i) for i in range(POW5_MAX_I + 1)],
             "5^i / 2^(ceil(log2(5^i)) - %d), for i in 0..%d"
             % (POW5_BITCOUNT, POW5_MAX_I))
        emit(fh, "dtoa_pow5_inv_split",
             [compute_inv_pow5(q) for q in range(POW5_INV_MAX_Q + 1)],
             "floor(2^(bitlen(5^q)-1+%d) / 5^q) + 1, for q in 0..%d"
             % (POW5_INV_BITCOUNT, POW5_INV_MAX_Q))
    sys.stderr.write("wrote %s\n" % out)


if __name__ == "__main__":
    main()
